insert into sch_sisauc.posto_graduacao values (1,'MARECHAL-DO-AR','MA');
insert into sch_sisauc.posto_graduacao values (2,'TENENTE-BRIGADEIRO','TB');
insert into sch_sisauc.posto_graduacao values (3,'MAJOR-BRIGADEIRO','MB');
insert into sch_sisauc.posto_graduacao values (4,'BRIGADEIRO','BR');
insert into sch_sisauc.posto_graduacao values (5,'CORONEL','CL');
insert into sch_sisauc.posto_graduacao values (6,'TENENTE-CORONEL','TC');
insert into sch_sisauc.posto_graduacao values (7,'MAJOR','MJ');
insert into sch_sisauc.posto_graduacao values (8,'CAPITÃO','CP');
insert into sch_sisauc.posto_graduacao values (9,'PRIMEIRO-TENENTE','1T');
insert into sch_sisauc.posto_graduacao values (10,'SEGUNDO-TENENTE','2T');
insert into sch_sisauc.posto_graduacao values (11,'ASPIRANTE-A-OFICIAL','AP');
insert into sch_sisauc.posto_graduacao values (12,'CADETE DO QUARTO ANO','C4');
insert into sch_sisauc.posto_graduacao values (13,'CADETE DO PRIMEIRO ANO','C1');
insert into sch_sisauc.posto_graduacao values (14,'MARECHALÍSSIMO','M1');
insert into sch_sisauc.posto_graduacao values (15,'ALUNA DO QFO (CIAAR)','F1');
insert into sch_sisauc.posto_graduacao values (16,'ALUNO DO CPCAR DO TERCEIRO ANO','A3');
insert into sch_sisauc.posto_graduacao values (17,'ALUNO DO CPCAR DO PRIMEIRO ANO','A1');
insert into sch_sisauc.posto_graduacao values (18,'ALUNO DO ITA DO PRIMEIRO ANO E ALUNO DO CPORAER','I1');
insert into sch_sisauc.posto_graduacao values (19,'SUBOFICIAL','SO');
insert into sch_sisauc.posto_graduacao values (20,'PRIMEIRO-SARGENTO','1S');
insert into sch_sisauc.posto_graduacao values (21,'SEGUNDO-SARGENTO','2S');
insert into sch_sisauc.posto_graduacao values (22,'TERCEIRO-SARGENTO','3S');
insert into sch_sisauc.posto_graduacao values (23,'SOLDADO DE PRIMEIRA CLASSE (ALUNO DO CFC)','P1');
insert into sch_sisauc.posto_graduacao values (24,'ALUNO DO CFS PRIMEIRA SÉRIE','G1');
insert into sch_sisauc.posto_graduacao values (25,'CABO','CB');
insert into sch_sisauc.posto_graduacao values (26,'SOLDADO DE PRIMEIRA CLASSE','S1');
insert into sch_sisauc.posto_graduacao values (27,'SOLDADO DE SEGUNDA CLASSE','S2');
insert into sch_sisauc.posto_graduacao values (28,'SOLDADO NÃO ENGAJADO ','SD');
insert into sch_sisauc.posto_graduacao values (29,'TAIFEIRO-MOR','TM');
insert into sch_sisauc.posto_graduacao values (30,'TAIFEIRO DE PRIMEIRA CLASSE','T1');
insert into sch_sisauc.posto_graduacao values (31,'TAIFEIRO DE SEGUNDA CLASSE','T2');
insert into sch_sisauc.posto_graduacao values (32,'ALUNO DO CFS QUARTA SÉRIE','G4');
insert into sch_sisauc.posto_graduacao values (33,'SOLDADO ESPECIALIZADO (EM EXTINÇÃO)','SE');
insert into sch_sisauc.posto_graduacao values (34,'ALUNO DO EAGS','GS');
insert into sch_sisauc.posto_graduacao values (35,'ALUNO DO CFS MODALIDADE ESPECIAL','GM');
insert into sch_sisauc.posto_graduacao values (45,'PENSIONISTA DO STM','CO');
insert into sch_sisauc.posto_graduacao values (46,'CADETE DO SEGUNDO ANO','C2');
insert into sch_sisauc.posto_graduacao values (47,'CADETE DO TERCEIRO ANO','C3');
insert into sch_sisauc.posto_graduacao values (48,'ALUNO DO CPCAR DO SEGUNDO ANO','A2');
insert into sch_sisauc.posto_graduacao values (50,'ALUNO DO ITA DO QUINTO ANO (ASP OF INF-ESTG ENG)','I5');
insert into sch_sisauc.posto_graduacao values (51,'ALUNO DO ITA DO QUARTO ANO (ASP OF INF-ESTG ENG)','I4');
insert into sch_sisauc.posto_graduacao values (52,'ALUNO DO ITA DO TERCEIRO ANO (ASP OF INF-ESTG ENG)','I3');
insert into sch_sisauc.posto_graduacao values (53,'ALUNO DO ITA DO SEGUNDO ANO(ASP OF INF DA RES. DA AER','I2');
insert into sch_sisauc.posto_graduacao values (55,'ALUNO DA EEAER QUARTA SÉRIE','E4');
insert into sch_sisauc.posto_graduacao values (56,'ALUNO DO CFS TERCEIRA SÉRIE','G3');
insert into sch_sisauc.posto_graduacao values (57,'ALUNO DO CFS SEGUNDA SÉRIE','G2');
insert into sch_sisauc.posto_graduacao values (58,'ALUNA DO QFG (CIAAR)','F2');
insert into sch_sisauc.posto_graduacao values (59,'ALUNO VTE','V1');
insert into sch_sisauc.posto_graduacao values (60,'ALUNO DO CURSO ESPECIALIZAÇÃO DE SOLDADO','S0');
insert into sch_sisauc.posto_graduacao values (61,'ALUNO EOEIG PRIMEIRO ANO','W1');
insert into sch_sisauc.posto_graduacao values (62,'ALUNO EOEIG SEGUNDO ANO','W2');
insert into sch_sisauc.posto_graduacao values (63,'SEGUNDO-TENENTE ESTAGIÁRIO','2E');
insert into sch_sisauc.posto_graduacao values (64,'PRIMEIRO-TENENTE ESTAGIÁRIO','1E');
insert into sch_sisauc.posto_graduacao values (100,'SEM POSTO','SP');

