insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('10101004','CONSULTAS',1);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('10102000','VISITAS',1);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('10103007','RECÉM-NASCIDO',1);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('10104003','UTI',1);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('10105000','REMOÇÃO / ACOMPANHAMENTO DE PACIENTE',1);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('10106006','OUTROS',1);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('20101007','AVALIAÇÕES / ACOMPANHAMENTOS',2);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('20102003','MONITORIZAÇÕES',2);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('20103000','REABILITAÇÕES - SESSÕES',2);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('20104006','TERAPÊUTICA',2);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('20105002','OUTROS',2);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('20201001','AVALIAÇÕES / ACOMPANHAMENTOS',3);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('20202008','MONITORIZAÇÕES',3);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('20203004','REABILITAÇÕES - SESSÕES',3);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('20204000','TERAPÊUTICA',3);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30101000','PROCEDIMENTOS',4);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30201004','LÁBIO',5);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30202000','BOCA',5);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30203007','LÍNGUA',5);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30204003','GLÂNDULAS SALIVARES',5);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30205000','FARINGE',5);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30206006','LARINGE',5);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30207002','TRAUMA CRÂNIO-MAXILO-FACIAL',5);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30208009','CIRURGIA REPARADORA E FUNCIONAL DA FACE',5);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30209005','SEQUELAS DE TRAUMA DA FACE',5);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30210003','FACE',5);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30211000','MANDÍBULA',5);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30212006','PESCOÇO',5);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30213002','TIREÓIDE',5);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30214009','PARATIREÓIDE',5);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30215005','CRÂNIO',5);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30301009','PÁLPEBRA',6);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30302005','CAVIDADE ORBITÁRIA',6);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30303001','CONJUNTIVA',6);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30304008','CÓRNEA',6);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30305004','CÂMARA ANTERIOR',6);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30306000','CRISTALINO',6);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30307007','CORPO VÍTREO',6);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30308003','ESCLERA',6);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30309000','BULBO OCULAR',6);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30310008','ÍRIS E CORPO CILIAR',6);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30311004','MÚSCULOS',6);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30312000','RETINA',6);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30313007','VIAS LACRIMAIS',6);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30401003','PAVILHÃO AURICULAR',7);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30402000','ORELHA EXTERNA',7);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30403006','ORELHA MÉDIA',7);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30404002','ORELHA INTERNA',7);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30501008','NARIZ',8);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30502004','SEIOS PARANASAIS',8);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30601002','PAREDE TORÁCICA',9);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30602009','MAMAS',9);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30701007','TRANSPLANTES CUTÂNEOS (COM MICROANASTOMOSES VASCULARES)',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30702003','TRANSPLANTES MÚSCULO-CUTÂNEOS (COM MICROANASTOMOSES VASCULARES)',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30703000','TRANSPLANTES MUSCULARES (COM MICROANASTOMOSES VASCULARES)',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30704006','TRANSPLANTES ÓSSEOS VASCULARIZADOS E TRANSPLANTES OSTEOMUSCULOCUTÂNEOS VASCULARIZADOS (COM MICROANASTOMOSES VASCULARES)',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30705002','MICROCIRURGIA NAS GRANDES RECONSTRUÇÕES DE CABEÇA E PESCOÇO, NAS EXTENSAS PERDAS DE SUBSTÂNCIA E NA ABLAÇÃO DE TUMORES AO NÍVEL DOS MEMBROS (COM MICROANASTOMOSES VASCULARES)',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30706009','REIMPLANTES E REVASCULARIZAÇÕES DOS MEMBROS',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30707005','TRANSPLANTES DE DEDOS DO PÉ PARA A MÃO',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30709008','TRAÇÃO',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30710006','RETIRADA DE MATERIAL DE SÍNTESE',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30711002','IMOBILIZAÇÕES PROVISÓRIAS - TALAS GESSADAS',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30712009','APARELHOS GESSADOS',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30713005','OUTROS PROCEDIMENTOS / PUNÇÕES',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30714001','RETIRADA DE CORPO ESTRANHO',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30715008','COLUNA VERTEBRAL',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30717000','ARTICULAÇÃO ESCÁPULO-UMERAL E CINTURA ESCAPULAR',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30718007','BRAÇO',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30719003','COTOVELO',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30720001','ANTEBRAÇO',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30721008','PUNHO',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30722004','MÃO',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30723000','CINTURA PÉLVICA',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30724007','ARTICULAÇÃO COXO-FEMORAL',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30725003','COXA / FÊMUR',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30726000','JOELHO',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30727006','PERNA',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30728002','TORNOZELO',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30729009','PÉ',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30730007','MÚSCULOS E FASCIAS',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30731003','TENDÕES, BURSAS E SINÓVIAS',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30732000','OSSOS',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30733006','PROCEDIMENTOS VIDEOARTROSCÓPICOS DE JOELHO',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30734002','PROCEDIMENTOS VIDEOARTROSCÓPICOS DE TORNOZELO',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30735009','PROCEDIMENTOS VIDEOARTROSCÓPICOS DE OMBRO',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30736005','PROCEDIMENTOS VIDEOARTROSCÓPICOS DE COTOVELO',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30737001','PROCEDIMENTOS VIDEOARTROSCÓPICOS DE PUNHO E TÚNEL DO CARPO',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30738008','PROCEDIMENTOS VIDEOARTROSCÓPICOS DE COXOFEMORAL',10);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30801001','TRAQUÉIA',11);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30802008','BRÔNQUIOS',11);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30803004','PULMÃO',11);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30804000','PLEURA',11);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30805007','MEDIASTINO',11);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30806003','DIAFRAGMA',11);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30901006','DEFEITOS CARDÍACOS CONGÊNITOS',12);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30902002','VALVOPLASTIAS',12);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30903009','CORONARIOPATIAS',12);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30904005','MARCA-PASSO',12);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30905001','OUTROS PROCEDIMENTOS',12);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30906008','CIRURGIA ARTERIAL',12);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30907004','CIRURGIA VENOSA',12);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30908000','FÍSTULAS ARTERIOVENOSAS CONGÊNITAS OU ADQUIRIDAS',12);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30909007','HEMODIÁLISE DE CURTA E LONGA PERMANÊNCIA',12);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30910005','CIRURGIA VASCULAR DE URGÊNCIA',12);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30911001','HEMODINÂMICA - CARDIOLOGIA INTERVENCIONISTA (PROCEDIMENTOS DIAGNÓSTICOS)',12);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30912008','HEMODINÂMICA - CARDIOLOGIA INTERVENCIONISTA (PROCEDIMENTOS TERAPÊUTICOS)',12);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30913004','ACESSOS VASCULARES',12);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30914000','CIRURGIA  LINFÁTICA',12);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30915007','PERICÁRDIO',12); 
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30916003','HIPOTERMIA',12);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30917000','MIOCÁRDIO',12);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('30918006','ELETROFISIOLOGIA CARDÍACA INVASIVA DIAGNÓSTICA E TERAPÊUTICA',12);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31001009','ESÔFAGO',13);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31002005','ESTÔMAGO',13);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31003001','INTESTINOS',13);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31004008','ÂNUS',13);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31005004','FÍGADO E VIAS BILIARES',13);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31006000','PÂNCREAS',13);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31007007','BAÇO',13);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31008003','PERITÔNIO',13);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31009000','ABDOME, PAREDE E CAVIDADE',13);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31101003','RIM, BACINETE E SUPRA-RENAL',14);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31102000','URETER',14);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31103006','BEXIGA',14);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31104002','URETRA',14);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31201008','PRÓSTATA E VESÍCULAS SEMINAIS',15);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31202004','ESCROTO',15);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31203000','TESTÍCULO',15);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31204007','EPIDÍDIMO',15);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31205003','CORDÃO ESPERMÁTICO',15);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31206000','PÊNIS',15);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31301002','VULVA',16);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31302009','VAGINA',16);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31303005','ÚTERO',16);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31304001','TUBAS',16);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31305008','OVÁRIOS',16);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31306004','PERÍNEO',16);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31307000','CAVIDADE E PAREDES PÉLVICAS',16);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31308007','INFERTILIDADE',16);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31309003','PARTOS E OUTROS PROCEDIMENTOS OBSTÉTRICOS',16);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31401007','ENCÉFALO',17);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31402003','MEDULA',17);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31403000','NERVOS PERIFÉRICOS',17);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31404006','NERVOS CRANIANOS',17);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31405002','SISTEMA NERVOSO AUTÔNOMO',17);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31501001','CÓRNEA',18);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31502008','CARDÍACO',18);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31503004','CARDIOPULMONAR',18);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31504000','PULMONAR',18);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31505007','HEPÁTICO',18);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31506003','RENAL',18);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31507000','PANCREÁTICO',18);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31601006','ACUPUNTURA',19);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('31602002','BLOQUEIOS ANESTÉSICOS DE NERVOS E ESTÍMULOS NEUROVASCULARES',19);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40101002','ECG - TE',20);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40102009','TUBO DIGESTIVO',20);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40103005','SISTEMA NERVOSO',20);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40104001','EXAMES ÓSTEO - MÚSCULO - ARTICULARES',20);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40105008','FUNÇÃO RESPIRATÓRIA',20);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40201007','ENDOSCOPIA DIAGNÓSTICA',21);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40202003','ENDOSCOPIA INTERVENCIONISTA',21);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40301001','BIOQUÍMICA',22);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40303004','COPROLOGIA',22);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40304000','HEMATOLOGIA LABORATORIAL',22);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40305007','ENDOCRINOLOGIA LABORATORIAL',22);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40306003','IMUNOLOGIA',22);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40309002','LÍQUIDOS (CEFALORRAQUEANO (LÍQUOR), SEMINAL, AMNIÓTICO, SINOVIAL E OUTROS)',22);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40310000','MICROBIOLOGIA',22);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40311007','URINÁLISE',22);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40312003','DIVERSOS',22);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40313000','TOXICOLOGIA / MONITORIZAÇÃO TERAPÊUTICA',22);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40314006','BIOLOGIA MOLECULAR',22);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40401006','TRANSFUSÃO',23);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40402002','PROCESSAMENTO',23);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40403009','PROCEDIMENTOS',23);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40501000','CITOGENÉTICA',24);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40502007','GENÉTICA BIOQUÍMICA',24);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40503003','GENÉTICA MOLECULAR',24);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40601005','PROCEDIMENTOS',25);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40701000','CARDIOVASCULAR - IN VIVO',26);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40702006','DIGESTIVO - IN VIVO',26);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40703002','ENDÓCRINO - IN VIVO',26);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40704009','GENITURINÁRIO - IN VIVO',26);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40705005','HEMATOLÓGICO - IN VIVO',26);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40706001','MÚSCULO - ESQUELÉTICO - IN VIVO',26);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40707008','NERVOSO - IN VIVO',26);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40708004','ONCOLOGIA / INFECTOLOGIA - IN VIVO',26);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40709000','RESPIRATÓRIO - IN VIVO',26);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40710009','TERAPIA - IN VIVO',26);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40711005','OUTROS - IN VIVO',26);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40801004','CRÂNIO E FACE',27);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40802000','COLUNA VERTEBRAL',27);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40803007','ESQUELETO TORÁCICO E MEMBROS SUPERIORES',27);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40804003','BACIA E MEMBROS INFERIORES',27);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40805000','TÓRAX',27);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40806006','SISTEMA DIGESTIVO',27);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40807002','SISTEMA URINÁRIO',27);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40808009','OUTROS EXAMES',27);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40809005','PROCEDIMENTOS ESPECIAIS',27);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40810003','NEURORRADIOLOGIA',27);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40811000','RADIOSCOPIA',27);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40812006','ANGIORRADIOLOGIA',27);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40813002','MÉTODOS INTERVENCIONISTAS / TERAPÊUTICOS POR IMAGEM',27);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40901009','ULTRA-SONOGRAFIA DIAGNÓSTICA',28);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('40902005','ULTRA-SONOGRAFIA INTERVENCIONISTA',28);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('41001001','TOMOGRAFIA COMPUTADORIZADA DIAGNÓSTICA',29);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('41002008','TOMOGRAFIA COMPUTADORIZADA INTERVENCIONISTA',29);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('41101006','RESSONÂNCIA MAGNÉTICA DIAGNÓSTICA',30);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('41102002','RESSONÂNCIA MAGNÉTICA INTERVENCIONISTA',30);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('41203003','PROCEDIMENTOS / TÉCNICAS DE RADIOTERAPIA EXTERNA',31);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('41204000','PROCEDIMENTOS SECUNDÁRIOS DE RADIOTERAPIA EXTERNA',31);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('41205006','PROCEDIMENTOS DE BRAQUITERAPIA',31);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('41206002','PROCEDIMENTOS SECUNDÁRIOS DE BRAQUITERAPIA',31);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('41301005','PROCEDIMENTOS',32);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('41401000','PROCEDIMENTOS',33);
insert into sch_sisauc.subgrupo (codigo, descricao, id_grupo) values ('41501004','PROCEDIMENTOS DIAGNÓSTICOS',34);
