insert into sch_sisauc.especialidade (sigla, nome) values('﻿ALEP','ALERGOLOGIA PEDIÁTRICA');
insert into sch_sisauc.especialidade (sigla, nome) values('ALER','ALERGOLOGIA');
insert into sch_sisauc.especialidade (sigla, nome) values('ANE','ANESTESIA PRÉ-OPERATÓRIA');
insert into sch_sisauc.especialidade (sigla, nome) values('ARRI','ARRITMIA CARDIOLOGICA');
insert into sch_sisauc.especialidade (sigla, nome) values('CBMF','CIRURGIA BUCO-MAXILO-FACIAL');
insert into sch_sisauc.especialidade (sigla, nome) values('CCAR','CIRURGIA CARDIACA');
insert into sch_sisauc.especialidade (sigla, nome) values('CDOR','CLINICA DA DOR');
insert into sch_sisauc.especialidade (sigla, nome) values('CGA','GERIATRIA');
insert into sch_sisauc.especialidade (sigla, nome) values('CGER','GERONTOLOGIA');
insert into sch_sisauc.especialidade (sigla, nome) values('CMED','CLINICA MÉDICA');
insert into sch_sisauc.especialidade (sigla, nome) values('CTOR','CIRURGIA TORÁCICA');
insert into sch_sisauc.especialidade (sigla, nome) values('CVP','CIRURGIA VASCULAR');
insert into sch_sisauc.especialidade (sigla, nome) values('DIRS','DIRETORIA DE SAÚDE');
insert into sch_sisauc.especialidade (sigla, nome) values('FIS','FISIOTERAPIA');
insert into sch_sisauc.especialidade (sigla, nome) values('HCAM','HOSPITAL DE CAMPANHA');
insert into sch_sisauc.especialidade (sigla, nome) values('HEPT','HEPATOLOGIA');
insert into sch_sisauc.especialidade (sigla, nome) values('INFE','INFECTOLOGIA');
insert into sch_sisauc.especialidade (sigla, nome) values('JSAU','JUNTAS DE SAÚDE');
insert into sch_sisauc.especialidade (sigla, nome) values('MED','MEDICO DE REFERENCIA');
insert into sch_sisauc.especialidade (sigla, nome) values('ORTO','ORTOPEDIA');
insert into sch_sisauc.especialidade (sigla, nome) values('OTOR','OTORRINOLARINGOLOGIA');
insert into sch_sisauc.especialidade (sigla, nome) values('RX','RADIOLOGIA');
insert into sch_sisauc.especialidade (sigla, nome) values('SCGE','CIRURGIA GERAL');
insert into sch_sisauc.especialidade (sigla, nome) values('SCPS','CIRURGIA PLÁSTICA');
insert into sch_sisauc.especialidade (sigla, nome) values('SDER','DERMATOLOGIA');
insert into sch_sisauc.especialidade (sigla, nome) values('SEND','ENDOCRINOLOGIA');
insert into sch_sisauc.especialidade (sigla, nome) values('SGE','GASTROENTEROLOGIA');
insert into sch_sisauc.especialidade (sigla, nome) values('SHE','HEMATOLOGIA');
insert into sch_sisauc.especialidade (sigla, nome) values('SNEF','NEFROLOGIA');
insert into sch_sisauc.especialidade (sigla, nome) values('SOFT','OFTALMOLOGIA');
insert into sch_sisauc.especialidade (sigla, nome) values('SONC','ONCOLOGIA');
insert into sch_sisauc.especialidade (sigla, nome) values('SPDI','PEDIATRIA');
insert into sch_sisauc.especialidade (sigla, nome) values('SPRO','PROCTOLOGIA');
insert into sch_sisauc.especialidade (sigla, nome) values('SPSI','PSIQUIATRIA');
insert into sch_sisauc.especialidade (sigla, nome) values('SREU','REUMATOLOGIA');
insert into sch_sisauc.especialidade (sigla, nome) values('SSMA','SUB-SEÇÃO DE MATERIAL');
insert into sch_sisauc.especialidade (sigla, nome) values('STE','TRIAGEM ENCAMINHAMENT');
insert into sch_sisauc.especialidade (sigla, nome) values('URO','UROLOGIA');
insert into sch_sisauc.especialidade (sigla, nome) values('CTBMF','CIRURGIA E TRAUMATOLOGIA BUCO-MAXILO-FACIAL');
insert into sch_sisauc.especialidade (sigla, nome) values('DEN','DENTÍSTICA');
insert into sch_sisauc.especialidade (sigla, nome) values('DTMDO','DISFUNÇÃO TÊMPERO-MANDIBULAR E DOR-OROFACIAL');
insert into sch_sisauc.especialidade (sigla, nome) values('ENDO','ENDODONTIA');
insert into sch_sisauc.especialidade (sigla, nome) values('ESTO','ESTOMATOLOGIA');
insert into sch_sisauc.especialidade (sigla, nome) values('ROI','RADIOLOGIA ODONTOLÓGICA E IMAGINOLOGIA');
insert into sch_sisauc.especialidade (sigla, nome) values('IMPL','IMPLANTODONTIA');
insert into sch_sisauc.especialidade (sigla, nome) values('ODONL','ODONTOLOGIA LEGAL');
insert into sch_sisauc.especialidade (sigla, nome) values('ODONG','ODONTOGERIATRIA');
insert into sch_sisauc.especialidade (sigla, nome) values('ODONP','ODONTOPEDIATRIA');
insert into sch_sisauc.especialidade (sigla, nome) values('ODONT','ODONTOLOGIA DO TRABALHO');
insert into sch_sisauc.especialidade (sigla, nome) values('OPNE','ODONTOLOGIA PARA PACIENTES COM NECESSIDADES ESPECIAIS');
insert into sch_sisauc.especialidade (sigla, nome) values('ORTO','ORTODONTIA');
insert into sch_sisauc.especialidade (sigla, nome) values('OFM','ORTOPEDIA FUNCIONAL DOS MAXILARES');
insert into sch_sisauc.especialidade (sigla, nome) values('PATB','PATOLOGIA BUCAL');
insert into sch_sisauc.especialidade (sigla, nome) values('PODO','PERIODONTIA');
insert into sch_sisauc.especialidade (sigla, nome) values('PBMF','PRÓTESE BUCO-MAXILO-FACIAL');
insert into sch_sisauc.especialidade (sigla, nome) values('PDEN','PRÓTESE DENTÁRIA');
insert into sch_sisauc.especialidade (sigla, nome) values('SCOL','SAÚDE COLETIVA');
insert into sch_sisauc.especialidade (sigla, nome) values('SPAR','SERVIÇO DE PRONTO ATENDIMENTO');
insert into sch_sisauc.especialidade (sigla, nome) values('CAR','CARDIOLOGIA');
insert into sch_sisauc.especialidade (sigla, nome) values('PSC','PSICOLOGIA');
insert into sch_sisauc.especialidade (sigla, nome) values('PNE','PNEUMOLOGIA');
insert into sch_sisauc.especialidade (sigla, nome) values('SNEC','NEUROCIRURGIA');
insert into sch_sisauc.especialidade (sigla, nome) values('NUT','NUTRIÇÃO E DIETÉTICA');
insert into sch_sisauc.especialidade (sigla, nome) values('GOB','GINECOLOGIA E OBSTETRÍCIA');
insert into sch_sisauc.especialidade (sigla, nome) values('FON','FONOAUDIOLOGIA');
insert into sch_sisauc.especialidade (sigla, nome) values('MTB','MEDICINA DO TRABALHO');
insert into sch_sisauc.especialidade (sigla, nome) values('CCP','CIRURGIA CABEÇA-PESCOÇO');
insert into sch_sisauc.especialidade (sigla, nome) values('CPD','CIRURGIA PEDIÁTRICA');
insert into sch_sisauc.especialidade (sigla, nome) values('ENF','ENFERMAGEM');
insert into sch_sisauc.especialidade (sigla, nome) values('MAST','MASTOLOGIA');
insert into sch_sisauc.especialidade (sigla, nome) values('FON/AU','FONOAUDIOLOGIA/AUDIOMETRIA');
