insert into sch_sisauc.grupo (codigo, descricao) values ('10100008','CONSULTAS');
insert into sch_sisauc.grupo (codigo, descricao) values ('20100000','PROCEDIMENTOS CLÍNICOS AMBULATORIAIS');
insert into sch_sisauc.grupo (codigo, descricao) values ('20200005','PROCEDIMENTOS CLÍNICOS HOSPITALARES');
insert into sch_sisauc.grupo (codigo, descricao) values ('30100003','PELE E TECIDO CELULAR SUBCUTÂNEO / ANEXOS');
insert into sch_sisauc.grupo (codigo, descricao) values ('30200008','CABEÇA E PESCOÇO');
insert into sch_sisauc.grupo (codigo, descricao) values ('30300002','OLHOS');
insert into sch_sisauc.grupo (codigo, descricao) values ('30400007','ORELHA');
insert into sch_sisauc.grupo (codigo, descricao) values ('30500001','NARIZ E SEIOS PARANASAIS');
insert into sch_sisauc.grupo (codigo, descricao) values ('30600006','PAREDE TORÁCICA');
insert into sch_sisauc.grupo (codigo, descricao) values ('30700000','SISTEMA MÚSCULO-ESQUELÉTICO E ARTICULAÇÕES');
insert into sch_sisauc.grupo (codigo, descricao) values ('30800005','SISTEMA RESPIRATÓRIO E MEDIASTINO');
insert into sch_sisauc.grupo (codigo, descricao) values ('30900000','SISTEMA CÁRDIO-CIRCULATÓRIO');
insert into sch_sisauc.grupo (codigo, descricao) values ('31000002','SISTEMA DIGESTIVO E ANEXOS');
insert into sch_sisauc.grupo (codigo, descricao) values ('31100007','SISTEMA URINÁRIO');
insert into sch_sisauc.grupo (codigo, descricao) values ('31200001','SISTEMA GENITAL E REPRODUTOR MASCULINO');
insert into sch_sisauc.grupo (codigo, descricao) values ('31300006','SISTEMA GENITAL E REPRODUTOR FEMININO');
insert into sch_sisauc.grupo (codigo, descricao) values ('31400000','SISTEMA NERVOSO - CENTRAL E PERIFÉRICO');
insert into sch_sisauc.grupo (codigo, descricao) values ('31500007','TRANSPLANTES DE ÓRGÃOS');
insert into sch_sisauc.grupo (codigo, descricao) values ('31600000','OUTROS PROCEDIMENTOS INVASIVOS');
insert into sch_sisauc.grupo (codigo, descricao) values ('40100006','ELETROFISIOLÓGICOS / MECÂNICOS E FUNCIONAIS');
insert into sch_sisauc.grupo (codigo, descricao) values ('40200000','ENDOSCÓPICOS');
insert into sch_sisauc.grupo (codigo, descricao) values ('40300005','MEDICINA LABORATORIAL');
insert into sch_sisauc.grupo (codigo, descricao) values ('40400000','MEDICINA TRANSFUSIONAL');
insert into sch_sisauc.grupo (codigo, descricao) values ('40500004','GENÉTICA');
insert into sch_sisauc.grupo (codigo, descricao) values ('40600009','ANATOMIA PATOLÓGICA E CITOPATOLOGIA');
insert into sch_sisauc.grupo (codigo, descricao) values ('40700003','MEDICINA NUCLEAR');
insert into sch_sisauc.grupo (codigo, descricao) values ('40800008','MÉTODOS DIAGNÓSTICOS POR IMAGEM');
insert into sch_sisauc.grupo (codigo, descricao) values ('40900002','ULTRASSONOGRAFIA');
insert into sch_sisauc.grupo (codigo, descricao) values ('41000005','TOMOGRAFIA COMPUTADORIZADA');
insert into sch_sisauc.grupo (codigo, descricao) values ('41100000','RESSONÂNCIA MAGNÉTICA');
insert into sch_sisauc.grupo (codigo, descricao) values ('41200004','RADIOTERAPIA');
insert into sch_sisauc.grupo (codigo, descricao) values ('41300009','EXAMES ESPECÍFICOS');
insert into sch_sisauc.grupo (codigo, descricao) values ('41400003','TESTES PARA DIAGNÓSTICOS');
insert into sch_sisauc.grupo (codigo, descricao) values ('41500008','OUTROS');
