insert into sch_sisauc.estado (nome, sigla, id_pais) values ('Acre','AC',1);
insert into sch_sisauc.estado (nome, sigla, id_pais) values ('Alagoas','AL',1);
insert into sch_sisauc.estado (nome, sigla, id_pais) values ('Amazonas','AM',1);
insert into sch_sisauc.estado (nome, sigla, id_pais) values ('Amapá','AP',1);
insert into sch_sisauc.estado (nome, sigla, id_pais) values ('Bahia','BA',1);
insert into sch_sisauc.estado (nome, sigla, id_pais) values ('Ceará','CE',1);
insert into sch_sisauc.estado (nome, sigla, id_pais) values ('Distrito Federal','DF',1);
insert into sch_sisauc.estado (nome, sigla, id_pais) values ('Espírito Santo','ES',1);
insert into sch_sisauc.estado (nome, sigla, id_pais) values ('Goiás','GO',1);
insert into sch_sisauc.estado (nome, sigla, id_pais) values ('Maranhão','MA',1);
insert into sch_sisauc.estado (nome, sigla, id_pais) values ('Minas Gerais','MG',1);
insert into sch_sisauc.estado (nome, sigla, id_pais) values ('Mato Grosso do Sul','MS',1);
insert into sch_sisauc.estado (nome, sigla, id_pais) values ('Mato Grosso','MT',1);
insert into sch_sisauc.estado (nome, sigla, id_pais) values ('Pará','PA',1);
insert into sch_sisauc.estado (nome, sigla, id_pais) values ('Paraíba','PB',1);
insert into sch_sisauc.estado (nome, sigla, id_pais) values ('Pernambuco','PE',1);
insert into sch_sisauc.estado (nome, sigla, id_pais) values ('Piauí','PI',1);
insert into sch_sisauc.estado (nome, sigla, id_pais) values ('Paraná','PR',1);
insert into sch_sisauc.estado (nome, sigla, id_pais) values ('Rio de Janeiro','RJ',1);
insert into sch_sisauc.estado (nome, sigla, id_pais) values ('Rio Grande do Norte','RN',1);
insert into sch_sisauc.estado (nome, sigla, id_pais) values ('Rondonia','RO',1);
insert into sch_sisauc.estado (nome, sigla, id_pais) values ('Roraima','RR',1);
insert into sch_sisauc.estado (nome, sigla, id_pais) values ('Rio Grande do Sul','RS',1);
insert into sch_sisauc.estado (nome, sigla, id_pais) values ('Santa Catarina','SC',1);
insert into sch_sisauc.estado (nome, sigla, id_pais) values ('Sergipe','SE',1);
insert into sch_sisauc.estado (nome, sigla, id_pais) values ('São Paulo','SP',1);
insert into sch_sisauc.estado (nome, sigla, id_pais) values ('Tocantins','TO',1);
