insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('COMGAR','COMANDO-GERAL DE OPERAÇÕES AÉREAS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('2/6 GAV','SEGUNDO ESQUADRÃO DO SEXTO GRUPO DE AVIAÇÃO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PAAN','PREFEITURA DE AERONÁUTICA DE ANÁPOLIS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('III FAE','TERCEIRA FORÇA AÉREA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('UNIFA','UNIVERSIDADE DA FORÇA AÉREA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('EPCAR','ESCOLA PREPARATÓRIA DE CADETES-DO-AR','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('BAGL','BASE AÉREA DO GALEÃO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('BASC','BASE AÉREA DE SANTA CRUZ','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1ªAUD/1ªCJ','1ªAUD/1ªCJ','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('COMAER','COMANDO DA AERONÁUTICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-MO','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: MACEIÓ','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-MQ','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: MACAPÁ','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-MT','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO DE MARTE','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-MY','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: MANICORÉ','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-NT','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: NATAL','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('BAAN','BASE AÉREA DE ANÁPOLIS','t','REGIONAL');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CIAAR','CENTRO DE INSTRUÇÃO E ADAPTAÇÃO DA AERONÁUTICA','t','REGIONAL');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CINDACTA II','SEGUNDO CENTRO INTEGRADO DE DEFESA AÉREA E CONTROLE DE TRAFEGO AÉREO','t','REGIONAL');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('BABV','BASE AÉREA DE BOA VISTA','t','REGIONAL');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('BACG','BASE AÉREA DE CAMPO GRANDE','t','REGIONAL');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('BAFL','BASE AÉREA DE FLORIANÓPOLIS','t','REGIONAL');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('BAFZ','BASE AÉREA DE FORTALEZA','t','REGIONAL');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('EEAR','ESCOLA DE ESPECIALISTAS DE AERONÁUTICA','t','REGIONAL');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('BAPV','BASE AÉREA DE PORTO VELHO','t','REGIONAL');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('BASV','BASE AÉREA DE SALVADOR','t','REGIONAL');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AFA','ACADEMIA DA FORÇA AÉREA','t','REGIONAL');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('BANT','BASE AÉREA DE NATAL','t','REGIONAL');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CLA','CENTRO DE LANÇAMENTO DE ALCÂNTARA','t','REGIONAL');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DIRSA','DIRETORIA DE SAÚDE DA AERONÁUTICA','t','REGIONAL');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('GIA-SJ','GRUPAMENTO DE INFRA-ESTRUTURA E APOIO DE SÃO JOSÉ DOS CAMPOS','t','REGIONAL');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('HABE','HOSPITAL DE AERONÁUTICA DE BELÉM','t','REGIONAL');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('HACO','HOSPITAL DE AERONÁUTICA DE CANOAS','t','REGIONAL');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('HAMN','HOSPITAL DE AERONÁUTICA DE MANAUS','t','REGIONAL');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('HARF','HOSPITAL DE AERONÁUTICA DE RECIFE','t','REGIONAL');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('HASP','HOSPITAL DE AERONÁUTICA DE SÃO PAULO','t','REGIONAL');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('HFAB','HOSPITAL DE FORÇA AÉREA DE BRASÍLIA','t','REGIONAL');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CTA','CENTRO TÉCNICO AEROESPACIAL','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('BASM','BASE AÉREA DE SANTA MARIA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DIRAP','DIRETORIA DE ADMINISTRAÇÃO DO PESSOAL','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('I COMAR','PRIMEIRO COMANDO AÉREO REGIONAL','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('II COMAR','SEGUNDO COMANDO AÉREO REGIONAL','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('III COMAR','TERCEIRO COMANDO AÉREO REGIONAL','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('IV COMAR','QUARTO COMANDO AÉREO REGIONAL','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('V COMAR','QUINTO COMANDO AÉREO REGIONAL','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('VI COMAR','SEXTO COMANDO AÉREO REGIONAL','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('VII COMAR','SÉTIMO COMANDO AÉREO REGIONAL','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1 ETA','Esquadrão de Transporte Aéreo','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1 GDAAE','PRIMEIRO GRUPO DE DEFESA ANTIAÉREA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1 GAVCA','PRIMEIRO GRUPO DE AVIAÇÃO DE CAÇA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1 GCC','PRIMEIRO GRUPO DE COMUNICAÇÕES E CONTROLE','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1 GDA','Grupo de Defesa Aérea','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1 GTT','Primeiro Grupo de Transporte de Tropa','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1/1 GCC','PRIMEIRO ESQUADRÃO DO PRIMEIRO GRUPO DE COMUNICAÇÕES E CONTROLE','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1/1 GT','PRIMEIRO ESQUADRÃO DO PRIMEIRO GRUPO DE TRANSPORTE','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1/10 GAV','PRIMEIRO ESQUADRÃO DO DÉCIMO GRUPO DE AVIAÇÃO - Esquadrão Poker','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1/11 GAV','PRIMEIRO ESQUADRÃO DO DÉCIMO PRIMEIRO GRUPO DE AVIAÇÃO – Esquadrão Gavião','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1/12 GAV','PRIMEIRO ESQUADRÃO DO DÉCIMO SEGUNDO GRUPO DE AVIAÇÃO - Esquadrão Horus','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1/14 GAV','PRIMEIRO ESQUADRÃO DO DÉCIMO QUARTO GRUPO DE AVIAÇÃO - Esquadrão Pampa','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1/15 GAV','Grupo de Aviação - Onça','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1/16 GAV','Primeiro Esquadrão do Décimo sexto Grupo de Aviação','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1/2 GT','Primeiro Esquadrão do Segundo Grupo de Transporte','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1/3 GAV','Primeiro do Terceiro Grupo de Aviação','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1/4 GAV-MN','Primeiro Esquadrão do Quarto Grupo de Aviação','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1/5 GAV','Primeiro Esquadrão do Quinto Grupo de Aviação','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1/6 GAV','Primeiro Esquadrão do Sexto Grupo de Aviação','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1/7 GAV','PRIMEIRO ESQUADRÃO DO SÉTIMO GRUPO DE AVIAÇÃO - Patrulha','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1/8 GAV','Primeiro do Oitava Grupo de Aviação','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1/9 GAV','Grupo de Aviação - Arara','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('2 ETA','Esquadrão de Transporte Aéreo','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('2/1 GCC','SEGUNDO ESQUADRÃO DO PRIMEIRO GRUPO DE COMUNICAÇÕES E CONTROLE','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('2/10 GAV','Grupo de Aviação - Esquadrão Pelicano','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('2/2 GT','Segundo Esquadrão do Segundo Grupo de Transporte','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('2/3 GAV','Grupo de Aviação - Esquadrão Grifo','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('2/5 GAV','SEGUNDO ESQUADRÃO DO QUINTO GRUPO DE AVIAÇÃO – Esquadrão Joker','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('ESQG','Esquadrão Guardião','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('2/7 GAV','Segundo Esquadrão do Sétimo Grupo de Aviação','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('2/8 GAV-PV','Segundo Esquadrão do Oitavo Grupo de Aviação','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('3 ETA','Terceiro Esquadrão de Transporte Aéreo','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('3/1 GCC','TERCEIRO ESQUADRÃO DO PRIMEIRO GRUPO DE COMUNICAÇÕES E CONTROLE','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('3/10 GAV','TERCEIRO ESQUADRÃO DO DÉCIMO GRUPO DE AVIAÇÃO - Esquadrão Centauro','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('3/3 GAV','Grupo de Aviação - Esquadrão Flecha','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('3/7 GAV','Grupo de Aviação - Esquadrão Netuno','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('3/8 GAV','TERCEIRO ESQUADRÃO DO OITAVO GRUPO DE AVIAÇÃO - Esquadrão Puma','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('4 ETA','Esquadrão de Transporte Aéreo','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('4/1 GCC','QUARTO ESQUADRÃO DO PRIMEIRO GRUPO DE COMUNICAÇÕES E CONTROLE','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('4/7 GAV','QUARTO ESQUADRÃO DO SÉTIMO GRUPO DE AVIAÇÃO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('5 ETA','QUINTO ESQUADRÃO DE TRANSPORTE AÉREO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('5/1 GCC','QUINTO ESQUADRÃO DO PRIMEIRO GRUPO DE COMUNICAÇÕES E CONTROLE','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('5/8 GAV','Quinto Esquadrão do Oitavo Grupo de Aviação','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('6 ETA','Sexto Esquadrão de Transporte Aéreo','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('7 ETA','Sétimo Esquadrão de Transporte Aéreo','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('7/8 GAV','Grupo de Aviação - Esquadrão Hárpia','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AD AFR SUL','ADITÂNCIA ÁFRICA DO SUL - ADIDO AERONÁUTICO DO BRASIL NA ÁFRICA DO SUL','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AD ALEMANHA','ADITÂNCIA ALEMANHA - ADIDO DO EXÉRCITO E AERONÁUTICO DO BRASIL NA ALEMANHA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AD ANGOLA','ADITÂNCIA ANGOLA - ADIDO DE DEFESA, NAVAL, DO EXÉRCITO E AERONÁUTICO DO BRASIL EM ANGOLA E SÃO TOMÉ E PRÍNCIPE','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AD ARGENT','ADITÂNCIA ARGENTINA - ADIDO DE DEFESA E AERONÁUTICO DO BRASIL NA ARGENTINA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AD BOLIVIA','ADITÂNCIA BOLÍVIA - ADIDO DE DEFESA E AERONÁUTICO DO BRASIL NA BOLÍVIA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AD CHILE','ADITÂNCIA CHILE - ADIDO AERONÁUTICO DO BRASIL NO CHILE','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AD CHINA','ADITÂNCIA CHINA - ADIDO DE DEFESA E AERONÁUTICO DO BRASIL NA CHINA, CORÉIA E VIETNÃ','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AD COLOMB','ADITÂNCIA COLÔMBIA - ADIDO AERONÁUTICO DO BRASIL NA COLÔMBIA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AD EEUU','ADITÂNCIA EUA - ADIDO DE DEFESA E AERONÁUTICO DO BRASIL NOS EUA E NO CANADÁ','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AD EQUADOR','ADITÂNCIA EQUADOR - ADIDO MILITAR DO BRASIL NO EQUADOR','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AD FRANCA','ADITÂNCIA FRANÇA - ADIDO DE DEFESA E AERONÁUTICO DO BRASIL NA FRANÇA E BÉLGICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AD INDIA','ADITÂNCIA ÍNDIA - ADIDO DE DEFESA, NAVAL, DO EXÉRCITO E AERONÁUTICO DO BRASIL NA ÍNDIA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1 CJM','1 CJM','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1 GAV','1 GAV','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('11 CJM/DF','11 CJM/DF','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AD INGL','ADITÂNCIA REINO UNIDO - ADIDO AERONÁUTICO DO BRASIL NA INGLATERRA, SUÉCIA E NORUEGA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AD IRA','ADITÂNCIA IRÃ - ADIDO DE DEFESA, NAVAL, DO EXÉRCITO E AERONÁUTICO DO BRASIL NO IRÃ','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AD ISRAEL','ADITÂNCIA ISRAEL - ADIDO DE DEFESA, NAVAL, DO EXÉRCITO E AERONÁUTICO DO BRASIL EM ISRAEL','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AD ITALIA','ADITÂNCIA ITÁLIA - ADIDO DE DEFESA E AERONÁUTICO DO BRASIL NA ITÁLIA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AD JAPAO','ADITÂNCIA JAPÃO - ADIDO DE DEFESA, NAVAL, DO EXÉRCITO E AERONÁUTICO DO BRASIL NO JAPÃO E NA INDONÉSIA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AD MEXICO','ADITÂNCIA MÉXICO - ADIDO DE DEFESA, NAVAL, DO EXÉRCITO E AERONÁUTICO DO BRASIL NO MÉXICO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AD MOCAMBIQUE','ADITÂNCIA MOÇAMBIQUE - ADIDO DE DEFESA, NAVAL, DO EXÉRCITO E AERONÁUTICO DO BRASIL EM MOÇAMBIQUE','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AD NAMIBIA','ADITÂNCIA NAMÍBIA - ADIDO DE DEFESA, NAVAL, DO EXÉRCITO E AERONÁUTICO DO BRASIL NA NAMÍBIA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AD NIGERIA','ADITÂNCIA NIGÉRIA - ADIDO DE DEFESA, NAVAL, DO EXÉRCITO E AERONÁUTICO DO BRASIL NA NIGÉRIA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AD PARAG','ADITÂNCIA PARAGUAI - ADIDO AERONÁUTICO DO BRASIL NO PARAGUAI','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AD PERU','ADITÂNCIA PERU - ADIDO AERONÁUTICO DO BRASIL NO PERU','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AD PORT','ADITÂNCIA PORTUGAL - ADIDO DO EXÉRCITO E AERONÁUTICO DO BRASIL EM PORTUGAL','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AD URUGUAI','ADITÂNCIA URUGUAI - ADIDO AERONÁUTICO DO BRASIL NO URUGUAI','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AD VENEZ','ADITÂNCIA VENEZUELA - ADIDO AERONÁUTICO DO BRASIL NA VENEZUELA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('ADIFA ESP','ADITÂNCIA ESPANHA - ADIDO NAVAL E AERONÁUTICO DO BRASIL NA ESPANHA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('ADIFA RUSS','ADITÂNCIA RÚSSIA - ADIDO DE DEFESA, NAVAL, DO EXÉRCITO E AERONÁUTICO DO BRASIL NA RÚSSIA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AGAFA','AGAFA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('ALBATROZ','CLUBE DOS SUBOFICIAIS E SARGENTOS DA AERONÁUTICA DE NATAL - ALBATROZ (Sede Social)','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AMVPR','AMVPR','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('ANAC','Agência Nacional de Aviação Civil','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('ASPAER','ASSESSORIA PARLAMENTAR DO COMANDANTE DA AERONÁUTICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('ASPR SP','ASPR SP','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AUD/1 CJM','AUD/1 CJM','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AUD/10CJM','AUD/10CJM','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AUD/4 CJM','AUD/4 CJM','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AUD/7ªCJM/','AUD/7ªCJM/','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('BAAF','BASE AÉREA DOS AFONSOS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('BABE','BASE AÉREA DE BELÉM','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('BABR','BASE AÉREA DE BRASÍLIA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('BACO','BASE AÉREA DE CANOAS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('BAMN','BASE AÉREA DE MANAUS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('BARF','BASE AÉREA DE RECIFE','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('BASP','BASE AÉREA DE SÃO PAULO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('BAST','Base Aérea de Santos','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('BINFAE AF','BATALHÃO DE INFANTARIA DE AERONÁUTICA ESPECIAL DE AFONSOS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('BINFAE BE','BATALHÃO DE INFANTARIA DE AERONÁUTICA ESPECIAL DE BELÉM','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('BINFAE BR','BATALHÃO DE INFANTARIA DE AERONÁUTICA ESPECIAL DE Brasília','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('BINFAE CO','BATALHÃO DE INFANTARIA DE AERONÁUTICA ESPECIAL DE CANOAS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('BINFAE GL','BATALHÃO DE INFANTARIA DE AERONÁUTICA ESPECIAL DE GALEÃO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('BINFAE MN','BATALHÃO DE INFANTARIA DE AERONÁUTICA ESPECIAL DE MANAUS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('BINFAE RF','BATALHÃO DE INFANTARIA DE AERONÁUTICA ESPECIAL DE RECIFE','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('BINFAE RJ','BATALHÃO DE INFANTARIA DE AERONÁUTICA ESPECIAL DO RIO DE JANEIRO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CABE','COMISSÃO AERONÁUTICA BRASILEIRA NA EUROPA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CABW','COMISSÃO AERONÁUTICA BRASILEIRA EM WASHINGTON','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CASSAB','CLUBE DOS SUBOFICIAIS E SARGENTOS DA AERONÁUTICA DE BRASÍLIA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CASSAS','CLUBE DOS SUBOFICIAIS E SARGENTOS DA AERONÁUTICA DE SALVADOR','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CASSASP','CLUBE ASSOCIATIVO DOS SUBOFICIAIS E SARGENTOS DA AERONÁUTICA DE SÃO PAULO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CATRE','CATRE','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CBNB','COLÉGIO BRIGADEIRO NEWTON BRAGA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CCA BR','Centro de Computação da Aeronáutica de Brasília','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CCA SJ','Centro de Computação da Aeronáutica de São José dos Campos','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CCPR','CCPR','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CCTAB','CLUBE DOS TAIFEIROS DA AERONÁUTICA DE BRASÍLIA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CDA','COMISSÃO DE DESPORTOS DA AERONÁUTICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CECAFA','CENTRO DE CATALOGAÇÃO DAS FORÇAS ARMADAS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CECAFA MD','CECAFA MD','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CECAN','CENTRO DO CORREIO AÉREO NACIONAL','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CECAT','CENTRO DE CATALOGAÇÃO DA AERONÁUTICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CECATI','COMISSÃO DE ESTUDOS E COORDENAÇÃO DE ASSUNTOS TÉCNICOS INTERNACIONAIS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CECOMSAER','CENTRO DE COMUNICAÇÃO SOCIAL DA AERONÁUTICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CELOG','CENTRO LOGÍSTICO DA AERONÁUTICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CEMAL','CENTRO DE MEDICINA AEROESPACIAL','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CENCIAR','CENCIAR','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CENDOC','CENTRO DE DOCUMENTAÇÃO E HISTÓRICO DA AERONÁUTICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CENIPA','CENTRO DE INVESTIGAÇÃO E PREVENÇÃO DE ACIDENTES AERONÁUTICOS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CFIAE','CAIXA DE FINANCIAMENTO IMOBILIÁRIO DA AERONÁUTICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CGABEG','CASA GERONTOLOGICA BRIG EDUARDO GOMES','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CGNA','Centro de Gerenciamento da Navegação Aérea','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CI CIAAR-L','CI CIAAR-L','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CIAER','CENTRO DE INTELIGÊNCIA DA AERONÁUTICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CID/JID','CID/JID','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CIEAR','CENTRO DE INSTRUÇÃO ESPECIALIZADA DA AERONÁUTICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CINDACTA','CINDACTA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CINDACTA I','PRIMEIRO CENTRO INTEGRADO DE DEFESA AÉREA E CONTROLE DE TRÁFEGO AÉREO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CINDACTA III','TERCEIRO CENTRO INTEGRADO DE DEFESA AÉREA E CONTROLO DE TRÁFEGO AÉREO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CINDACTA IV','QUARTO CENTRO INTEGRADO DE DEFESA AÉREA E CONTROLO DE TRÁFEGO AÉREO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CISCEA','COMISSÃO DE IMPLANTAÇÃO DO SISTEMA DE CONTROLE DO ESPAÇO AÉREO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CLBI','CENTRO DE LANÇAMENTO DA BARREIRA DO INFERNO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CLUBAER','CLUBE DE AERONÁUTICA DE BRASÍLIA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CLUBAER-RJ','CLUBE DE AERONÁUTICA - RIO DE JANEIRO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CMB','CMB','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CMBH','CMBH','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CMCG','CMCG','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CMCR','CMCR','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CMFZ','CMFZ','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CMJF','CMJF','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CMM','CMM','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CMPA','CMPA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CMRF','CMRF','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CMRJ','CMRJ','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CMS','CMS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CMSM','CMSM','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('COAGB','Cassino dos Oficiais da Aeronáutica da Guarnição de Belém','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('COGA','CENTRO SOCIAL DE OFICIAIS DA AERONÁUTICA DA GUARNIÇÃO DOS AFONSOS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('COJAER','CONSULTORIA JURÍDICA ADJUNTA DO COMANDO DA AERONÁUTICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('COMARA','COMISSÃO DE AEROPORTOS DA REGIÃO AMAZÔNICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('COMDABRA','COMANDO DE DEFESA AEROESPACIAL BRASILEIRO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('COMEXER','COMEXER','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('COMF CELMA','COMF CELMA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('COMFIREM-AEROELETRÔNICA','COMISSÃO DE FISCALIZAÇÃO E RECEBIMENTO DE MATERIAL E SERVIÇOS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('COMFIREM-CELMA','COMISSÃO DE FISCALIZAÇÃO E RECEBIMENTO DE MATERIAL JUNTO À CIA. CELMA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('COMFIREM-EMBRAER','COMISSÃO DE FISC. E EXECUÇÃO DE CONTRATOS JUNTO À EMBRAER','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('COMFIREM-MRR','COMISSÃO DE FISC. E EXEC. DE CONT. JUNTO À CIA. MOTORES ROLLS-ROYCE S/A','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('COMGAP','COMANDO-GERAL DE APOIO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('COMGEP','COMANDO-GERAL DO PESSOAL','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('COPAC','COMISSÃO COORDENADORA DO PROGRAMA AERONAVE DE COMBATE','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CPBV','Campo de Provas Brigadeiro Velloso','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CPO','COMISSÃO DE PROMOÇÕES DE OFICIAIS DA AERONÁUTICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CPOR SJ','CENTRO DE PREPARAÇÃO DE OFICIAIS DA RESERVA DA AERONÁUTICA DE SÃO JOSÉ DOS CAMPOS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CSSA-RJ','CLUBE DOS SUBOFICIAIS E SARGENTOS, DA AERONÁUTICA DO RIO DE JANEIRO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CTDA-RJ','CLUBE DOS TAIFEIROS DA AERONÁUTICA DO RIO DE JANEIRO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DAC','DAC','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DACO MN','DACO MN','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DARJ','DEPÓSITO DE AERONÁUTICA DO RIO DE JANEIRO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DCI','DEPÓSITO CENTRAL DE INTENDÊNCIA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DCTA','DEPARTAMENTO DE CIÊNCIA E TECNOLOGIA AEROESPACIAL','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DECEA','DEPARTAMENTO DE CONTROLE DO ESPAÇO AÉREO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DEPENS','DEPARTAMENTO DE ENSINO DA AERONÁUTICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DESTAE-CV','DESTACAMENTO DE AERONÁUTICA DE CARAVELAS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DESTAE-FN','DESTACAMENTO DE AERONÁUTICA DE FERNANDO DE NORONHA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DESTAE-MQ','DESTACAMENTO DE AERONÁUTICA DE MACAPÁ','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DESTAE-MS','DESTACAMENTO DE AERONÁUTICA DE MOSSORÓ','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DIRENG','DIRETORIA DE ENGENHARIA DA AERONÁUTICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DIRINT','DIRETORIA DE INTENDÊNCIA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DIRMA','DIRMA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DIRMAB','DIRETORIA DE MATERIAL AERONÁUTICO E BÉLICO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DIRMAB *','DIRMAB *','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DPVDT-71','DESTACAMENTO DE PROTEÇÃO AO VÔO, DETECÇÃO E TELECOMUNICAÇÕES: MANAUS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DPVDT-74','DESTACAMENTO DE PROTEÇÃO AO VÔO, DETECÇÃO E TELECOMUNICAÇÕES: TABATINGA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DSM-MN','DESTACAMENTO DE SUPRIMENTO E MANUTENÇÃO DE MANAUS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DSTAECV','DSTAECV','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DSTAEEI','DSTAEEI','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DSTAEFN','DSTAEFN','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DSTAEUA','DSTAEUA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DSTAEVH','DSTAEVH','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-AA','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: CONCEIÇÃO DO ARAGUIA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-AF','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO DOS AFONSOS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-AN','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: ANÁPOLIS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-AR','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: ARACAJU','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-BE','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: BELÉM','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-BI','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO DE BACACHERI','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-BQ','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: BARBACENA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-BR','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: BRASÍLIA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-BV','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: BOA VISTA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-BW','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: BARRA DO GARÇAS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-CC','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: CACHIMBO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-CDT','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: CATANDUVAS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-CF','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: CONFINS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-CG','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: CAMPO GRANDE','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-CGU','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: CANGUÇU','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-CO','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: CANOAS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-CR','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: CORUMBÁ','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-CT','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: CURITIBA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-CTD','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: CATANDUVAS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-CY','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: CUIABÁ','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-CZ','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: CRUZEIRO DO SUL','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-EG','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: EDUARDO GOMES','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-EI','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: EIRUNEPÉ','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-EK','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: JACAREACANGA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-EP','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: PORTO ESPERIDIÃO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-FA','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO DE SÃO FÉLIX DO ARAGUAIA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-FI','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: FOZ DO IGUAÇU','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-FL','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: FLORIANÓPOLIS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-FN','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: FERNANDO DE NORONHA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-FX','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: SÃO FÉLIX DO XINGU','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-FZ','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: FORTALEZA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-GA','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: GAMA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-GI','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: CHAPADA DOS GUIMARÃES','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-GL','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO DO GALEÃO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-GM','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: GUAJARÁ-MIRIM','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-GW','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO DE GUARATINGUETÁ','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-IZ','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: IMPERATRIZ','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-JGI','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO DE JARAGUARI','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-LP','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: BOM JESUS DA LAPA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-LS','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: LAGOA SANTA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-MDI','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: MORRO DA IGREJA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-MN','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: MANAUS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-OI','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: OIAPOQUE','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-PA','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: PORTO ALEGRE','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-PCO','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: PICO DO COUTO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-PIE','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: SERRA DA PIEDADE','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-PL','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: PETROLINA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-PS','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: PORTO SEGURO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-PV','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: PORTO VELHO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-RB','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: RIO BRANCO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-RF','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: RECIFE','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-SC','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO DE SANTA CRUZ','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-SI','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO DE SINOP','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-SJ','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: SÃO JOSÉ DOS CAMPOS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-SL','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: SÃO LUÍS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-SM','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO DE SANTA MARIA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-SN','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: SANTARÉM','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-SP','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO DE SÃO PAULO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-SRO','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: SÃO ROQUE','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-ST','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO DE SANTOS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-STA','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: SANTA TERESA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-STI','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: SANTIAGO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-SV','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: SALVADOR','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-TF','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: TEFÉ','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-TNB','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: TANABI','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-TRM','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: TRÊS MARIAS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-TT','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: TABATINGA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-UA','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: SÃO GABRIEL DA CACHOEIRA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-UG','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: URUGUAIANA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-VH','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: VILHENA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEA-YS','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO: PIRASSUNUNGA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTCEATM-RJ','DESTACAMENTO DE CONTROLE DO ESPAÇO AÉREO E TELEMÁTICA DO RIO DE JANEIRO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTI','DIRETORIA DE TECNOLOGIA DA INFORMAÇÃO DA AERONÁUTICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DTS','DESTACAMENTO DE TELECOMUNICAÇÕES POR SATÉLITE','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('EAOAR','ESCOLA DE APERFEIÇOAMENTO DE OFICIAIS DA AERONAÚTICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('EAPAC','ESCOLA DE APERFEIÇOAMENTO E PREPARAÇÃO DA AERONÁUTICA CIVIL','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('EAS','ESQUADRÃO AEROTERRESTRE DE SALVAMENTO (PARA-SAR)','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('EAS CG','EAS CG','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('ECEMAR','ESCOLA DE COMANDO E ESTADO MAIOR DA AERONAÚTICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('ECEME','ECEME','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('EDA','ESQUADRÃO DE DEMONSTRAÇÃO AÉREA - Esquadrilha da Fumaça','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('EGN','EGN','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('EMAER','ESTADO-MAIOR DA AERONÁUTICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('ESG','ESCOLA SUPERIOR DE GUERRA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('ETRB','Escola Ten Rego Barros','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('FAYS','FAZENDA DE AERONÁUTICA DE PIRASSUNUNGA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('GABAER','GABINETE DO COMANDANTE DA AERONÁUTICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('GAC-EMBRAER','GRUPO DE ACOMPANHAMENTO E CONTROLE NA EMBRAER','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('GAC-HB','GAC-HB','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('GAC-MECTRO','GAC-MECTRO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('GAP BR','Grupo de Apoio de Brasília','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('GAP RJ','Grupo de Apoio do Rio de Janeiro','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('GAP-BR','GAP-BR','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('GEIV','GRUPO ESPECIAL DE INSPEÇÃO EM VOO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('GITE','Grupo de Instrução Tático e Especializada','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('GSIPR','GSIPR','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('GTE','GRUPO DE TRANSPORT ESPECIAL','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('HAAF','HOSPITAL DE AERONÁUTICA DOS AFONSOS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('HCA','HOSPITAL CENTRAL DA AERONÁUTICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('HFA','Hospital das Forças Armadas','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('HFAG','HOSPITAL DE FORÇA AÉREA DO GALEÃO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('I FAE','PRIMEIRA FORÇA AÉREA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('IAE','INSTITUTO DE AERONÁUTICA E ESPAÇO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('ICA','INSTITUTO DE CARTOGRAFIA AERONÁUTICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('ICEA','INSTITUTO DE CONTROLE DO ESPAÇO AÉREO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('IEAV','INSTITUTO DE ESTUDOS AVANÇADOS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('IFI','INSTITUTO DE FOMENTO E COORDENAÇÃO INDUSTRIAL','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('II FAE','Segunda Força Aérea','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('ILA','INSTITUTO DE LOGÍSTICA DA AERONÁUTICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('IMAE','INSTITUTO MEDICINA AEROESPACIAL BRIGADEIRO MÉDICO ROBERTO TEIXEIRA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('INCAER','INSTITUTO HISTÓRICO-CULTURAL DA AERONÁUTICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('IPA','INSTITUTO DE PSICOLOGIA DA AERONÁUTICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('IPEV','INSTITUTO DE PESQUISA E ENSAIOS EM VÔO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('ITA','INSTITUTO TECNOLÓGICO DE AERONÁUTICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('LAQFA','LABORATÓRIO QUÍMICO E FARMACÊUTICO DA AERONÁUTICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('MD','MINISTÉRIO DA DEFESA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('MDEFESA','MDEFESA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('MISSAO BR','MISSAO BR','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('MISSAO EXT','MISSAO EXT','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('MTAB','MTAB','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('MUSAL','MUSEU AEROESPACIAL','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('NuBAAA','Núcleo da Brigada de Artilharia Antiaérea deAutodefesa','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('NUBAST','NÚCLEO DA BASE AÉREA DE SANTOS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('NUDTS BR','NUDTS BR','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('OABR','ODONTOCLÍNICA DE AERONÁUTICA DE BRASÍLIA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('OACI','OACI','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('OARF','ODONTOCLÍNICA DE AERONÁUTICA DE RECIFE','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('OASD','ODONTOCLÍNICA DE AERONÁUTICA SANTOS-DUMONT','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('ONU','ONU','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PAAF','Prefeitura de Aeronáutica dos Afonsos','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PAAK','PREFEITURA DE AERONÁUTICA DE ALCÂNTARA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PABE','Prefeitura de Aeronáutica de Belém','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PABH','PREFEITURA DE AERONÁUTICA DE BELO HORIZONTE','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PABQ','PREFEITURA DE AERONÁUTICA DE BARBACENA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PABR','Prefeitura de Aeronáutica de Brasília','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PABV','Prefeitura de Aeronáutica de Boa Vista','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PACG','Prefeitura de Aeronáutica de Campo Grande','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PACO','Prefeitura de Aeronáutica de Canoas','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PACT','PREFEITURA DE AERONÁUTICA DE CURITIBA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PAFL','Preferia da Base Aérea de Florianópolis','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PAFZ','Prefeitura de Aeronáutica de Fortaleza','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PAGL','Prefeitura de Aeronáutica do Galeão','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PAGW','PREFEITURA DE AERONÁUTICA DE GUARATINGUETÁ','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PALS','PREFEITURA DE AERONÁUTICA DE LAGOA SANTA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PAMA-AF','PARQUE DE MATERIAL DOS AFONSOS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PAMA-GL','PARQUE DE MATERIAL DO GALEÃO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PAMA-LS','PARQUE DE MATERIAL DE LAGOA SANTA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PAMA-RF','PARQUE DE MATERIAL DE RECIFE','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PAMA-SP','PARQUE DE MATERIAL DE SÃO PAULO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PAMB-RJ','PARQUE DE MATERIAL BÉLICO DE AERONÁUTICA DO RIO DE JANEIRO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PAME-RJ','PARQUE DE MATERIAL ELETRÔNICO DA AERONÁUTICA DO RIO DE JANEIRO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PAMN','Prefeitura de Aeronáutica de Manaus','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PANT','Prefeitura de Aeronáutica de Natal','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PAPV','Prefeitura de Aeronáutica de Porto Velho','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PARF','Prefeitura de Aeronáutica de Recife','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PASC','Prefeitura de Aeronáutica de Santa Cruz','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PASJ','PREFEITURA DE AERONÁUTICA DE SÃO JOSÉ DOS CAMPOS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PASM','Prefeitura de Aeronáutica de Santa Maria','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PASP','Prefeitura de Aeronáutica de São Paulo','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PAST','PREFEITURA DE AERONÁUTICA DE SANTOS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PASV','Prefeitura de Aeronáutica de Salvador','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PAYS','PREFEITURA DE AERONÁUTICA DE PIRASSUNUNGA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PIPAR','PAGADORIA DE INATIVOS E PENSIONISTAS DA AERONÁUTICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PIPAR-INAT','PIPAR-INAT','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('Policlinica','POLICLÍNICA DE AERONÁUTICA DA BARRA DA TIJUCA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PR','Presidência da República','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('REMABI','REMABI','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SAGAB','SAGAB','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SBDA','SOCIEDADE BRASILEIRA DE DIREITO AEROESPACIAL','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SDAB','SUBDIRETORIA DE ABASTECIMENTO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SECONSIPAM','SECRETARIA EXECUTIVA DO CONSELHO DELIBERATIVO DO SISTEMA DE PROTEÇÃO DA AMAZÔNIA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SEFA','SECRETARIA DE ECONOMIA E FINANÇAS DA AERONÁUTICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SEGECAE','SERVIÇO GERAL DE CORRESPONDÊNCIA E ARQUIVO DA AERONÁUTICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SERIPA I','PRIMEIRO SERVIÇO REGIONAL DE INVESTIGAÇÃO E PREVENÇÃO DE ACIDENTES AERONÁUTICOS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SERIPA II','SEGUNDO SERVIÇO REGIONAL DE INVESTIGAÇÃO E PREVENÇÃO DE ACIDENTES AERONÁUTICOS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SERIPA III','TERCEIRO SERVIÇO REGIONAL DE INVESTIGAÇÃO E PREVENÇÃO DE ACIDENTES AERONÁUTICOS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SERIPA IV','QUARTO SERVIÇO REGIONAL DE INVESTIGAÇÃO E PREVENÇÃO DE ACIDENTES AERONÁUTICOS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SERIPA V','QUINTO SERVIÇO REGIONAL DE INVESTIGAÇÃO E PREVENÇÃO DE ACIDENTES AERONÁUTICOS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SERIPA VI','SEXTO SERVIÇO REGIONAL DE INVESTIGAÇÃO E PREVENÇÃO DE ACIDENTES AERONÁUTICOS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SERIPA VII','SÉTIMO SERVIÇO REGIONAL DE INVESTIGAÇÃO E PREVENÇÃO DE ACIDENTES AERONÁUTICOS','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SERSA 1','SERVIÇO REGIONAL DE SAÚDE 1','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SERSA 2','SERVIÇO REGIONAL DE SAÚDE 2','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SERSA 3','SERVIÇO REGIONAL DE SAÚDE 3','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SERSA 4','SERVIÇO REGIONAL DE SAÚDE 4','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SERSA 5','SERVIÇO REGIONAL DE SAÚDE 5','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SERSA 6','SERVIÇO REGIONAL DE SAÚDE 6','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SERSA 7','SERVIÇO REGIONAL DE SAÚDE 7','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SRPV MN','SERVIÇO REGIONAL DE PROTEÇÃO AO VOO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SRPV SP','SERVIÇO REGIONAL DE PROTEÇÃO AO VOO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('STM','SUPERIOR TRIBUNAL MILITAR','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('TRF1','TRF1','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('TRF2REGIAO','TRF2REGIAO','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('V FAE','Quinta Força Aérea','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('VIC-PRAER','VIC-PRAER','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('VPR','VICE-PRESIDÊNCIA DA REPÚBLICA','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('ASOCEA','Assessoria de Segurança Operacional do Controle do Espaço Aéreo','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CCA RJ','Centro de Computação da Aeronáutica do Rio de Janeiro','t','SUBORDINADA');



insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('GAPS','Grupamento de Apoio da Saúde','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CTLA','Centro de Transporte Logístico da Aeronáutica','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('NuBDAAE','Núcleo da Brigada de Defesa Antiaérea','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('2 GDAAE','Segundo Grupo de Defesa Antiaérea','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CO-DCTA','Comissão de Obras do Departamento de Ciência e Tecnologia Aeroespacial','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('GAC-MECTRON','Grupo de Acompanhamento e Controle das Atividades Relativas ao Radar SCP-01 na Mectron','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('GAL','Grupamento de Apoio Logístico','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('NUPAMA-RF','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DRACCT','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SAC SBEK','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AUD/7ªCJM/RF','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('BABH','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DPVPL','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SRSP-UPBCO','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1/5 GAV-FZ','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DPVPS','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('EOEAER','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SAC SBMT','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CFPM','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DEPED','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AUD/4 CJM MG','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AUD/5ªCJM/CR','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SRPV BE','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('NU3GDAAE','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('COMF EMBRA','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DPVDT-11','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SAE','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1/13 GAV','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SAC SBFL','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('HABR','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SRPV BR','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SAC SBFZ','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DIRINFE','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DEPV','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('NUCOPE-P','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SRPV RF','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SRPV RJ','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DPVBH','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('NCINDACT3','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('EMFA','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SAC SBCP','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('4 CJM','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('5 GAV','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1/11 GAV ST','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1 ALADA','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('2/8 GAV','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SAC SBCR','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('ADIFA ISRA','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('GICLA','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SAC SBCT','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('NUIAOP','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DPVDT-73','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('ALA435','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('VI FAE','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SAC SBUL','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SAC SBCY','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CABSP','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SAC SBME','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1/4 GAV','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('5/1 GCC-FZ','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('ADIAER','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CI CIAAR-LS','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('COMAT','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1 GAE','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('AUD/10CJM RJ','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SAC SBTT','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CIGAR','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('TRF2REGIAO/RJ','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('COMTA','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SAC SBAT','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('NUCINDACTA','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DPVLP','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SAC SBSV','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('BAPA','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SAC SBSP','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('NUBABH','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DPVGO','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('2 ELO','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SAC SBBR','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SAC SBBV','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('2/7 ETA','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SAC SBBH','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('JJAER','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('IAC','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1/7/8 GAV','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('EOEIG','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('NU 1/8 GAV','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1/7 ETA','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SRSP-UPSTN','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SERAC 1','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('RBJID','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SERAC 4','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SERAC 5','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('RECABI','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SERAC 2','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SERAC 3','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DPVDT-24','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CMPR','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SERAC 6','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DPVDT-25','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SERAC 7','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DPVDT-22','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DMI SP','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('COMFAP','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('PAMA-BE','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SAC SBGR','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SAC SBGO','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DPVRJ','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SBFL','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SAC SBIL','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('GEICAMP','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SRPV PA','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('EAS AF','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('DPVKP','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SAC SBPA','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('NCD3-DPVFZ','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SAC SBIH','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SBFZ','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CURSO BR','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('NUCOMDABRA','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('ERC','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SRRJ-ZWN23','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('1/4 GAV-NT','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('CECIA','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('2/8 GAV-RF','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('NUCLA','','t','SUBORDINADA');
insert into sch_sisauc.organizacao_militar (sigla, nome, ativo, tipo_om) values ('SAC SBPL','','t','SUBORDINADA');


