insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Elegibilidade',1003,'A ADMISSÃO DO BENEFICIÁRIO NO PRESTADOR OCORREU ANTES DA INCLUSÃO DO BENEFICIÁRIO NA OPERADORA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Elegibilidade',1004,'SOLICITAÇÃO ANTERIOR À INCLUSÃO DO BENEFICIÁRIO','true','false','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Elegibilidade',1005,'ATENDIMENTO ANTERIOR À INCLUSÃO DO BENEFICIÁRIO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Elegibilidade',1006,'ATENDIMENTO APÓS O DESLIGAMENTO DO BENEFICIÁRIO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Elegibilidade',1008,'ASSINATURA DIVERGENTE','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Elegibilidade',1010,'ASSINATURA DO TITULAR / RESPONSÁVEL INEXISTENTE','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Elegibilidade',1011,'IDENTIFICAÇÃO DO BENEFICIÁRIO NÃO CONSISTENTE','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Elegibilidade',1012,'SERVIÇO PROFISSIONAL HOSPITALAR NÃO É COBERTO PELO PLANO DO BENEFICIÁRIO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Elegibilidade',1013,'CADASTRO DO BENEFICIÁRIO COM PROBLEMAS','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Elegibilidade',1014,'BENEFICIÁRIO COM DATA DE EXCLUSÃO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Elegibilidade',1016,'BENEFICIÁRIO COM ATENDIMENTO SUSPENSO','true','false','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Elegibilidade',1019,'FAMÍLIA DO BENEFICIÁRIO COM ATENDIMENTO SUSPENSO','true','false','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Elegibilidade',1023,'NOME DO TITULAR INVÁLIDO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Protocolo',1101,'QUANTIDADE DE GUIAS INFORMADAS NO PROTOCOLO DIFERENTE DAS CADASTRADAS','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Protocolo',1104,'VALOR TOTAL DO PROTOCOLO DIFERENTE DO VALOR TOTAL DAS GUIAS','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Prestador',1201,'ATENDIMENTO FORA DA VIGÊNCIA DO CONTRATO COM O CREDENCIADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Prestador',1203,'CÓDIGO PRESTADOR INVÁLIDO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Prestador',1204,'ADMISSÃO ANTERIOR À INCLUSÃO DO CREDENCIADO NA REDE','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Prestador',1205,'ADMISSÃO APÓS O DESLIGAMENTO DO CREDENCIADO DA REDE','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Prestador',1206,'CPF / CNPJ INVÁLIDO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Prestador',1208,'SOLICITAÇÃO ANTERIOR À INCLUSÃO DO CREDENCIADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Prestador',1209,'SOLICITAÇÃO APÓS O DESLIGAMENTO DO CREDENCIADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Prestador',1210,'SOLICITANTE CREDENCIADO NÃO CADASTRADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Prestador',1211,'ASSINATURA / CARIMBO DO CREDENCIADO INEXISTENTE','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Prestador',1212,'ATENDIMENTO/ REFERÊNCIA FORA DA VIGÊNCIA DO CONTRATO DO PRESTADOR','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Prestador',1213,'CBO (ESPECIALIDADE) INVÁLIDO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Prestador',1214,'CREDENCIADO NÃO HABILITADO A REALIZAR O PROCEDIMENTO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Prestador',1216,'ESPECIALIDADE NÃO CADASTRADA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Prestador',1217,'ESPECIALIDADE NÃO CADASTRADA PARA O PRESTADOR','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Guia',1301,'TIPO GUIA INVÁLIDO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Guia',1303,'NÃO EXISTE O NÚMERO GUIA PRINCIPAL INFORMADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Guia',1304,'COBRANÇA EM GUIA INDEVIDA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Guia',1305,'ITEM PAGO EM OUTRA GUIA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Guia',1307,'NÚMERO DA GUIA INVÁLIDO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Guia',1308,'GUIA JÁ APRESENTADA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Guia',1309,'PROCEDIMENTO CONTRATADO NÃO ESTÁ DE ACORDO COM O TIPO DE GUIA UTILIZADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Guia',1310,'SERVIÇO DO TIPO CIRÚRGICO E INVASIVO. EQUIPE MÉDICA NÃO INFORMADA NA GUIA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Guia',1311,'PRESTADOR EXECUTANTE NÃO INFORMADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Guia',1313,'GUIA COM RASURA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Guia',1314,'GUIA SEM ASSINATURA E/OU CARIMBO DO CREDENCIADO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Guia',1315,'GUIA SEM DATA DO ATO CIRÚRGICO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Guia',1316,'GUIA COM LOCAL DE ATENDIMENTO PREENCHIDO INCORRETAMENTE.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Guia',1317,'GUIA SEM DATA DO ATENDIMENTO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Guia',1318,'GUIA COM CÓDIGO DE SERVIÇO PREENCHIDO INCORRETAMENTE.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Guia',1319,'GUIA SEM ASSINATURA DO ASSISTIDO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Guia',1320,'IDENTIFICAÇÃO DO ASSISTIDO INCOMPLETA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Guia',1321,'VALIDADE DA GUIA EXPIRADA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Autorização / Solicitação',1401,'ACOMODAÇÃO NÃO AUTORIZADA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Autorização / Solicitação',1402,'PROCEDIMENTO NÃO AUTORIZADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Autorização / Solicitação',1404,'NÃO EXISTE GUIA DE AUTORIZAÇÃO RELACIONADA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Autorização / Solicitação',1405,'DATA DE VALIDADE DA GUIA DE AUTORIZAÇÃO É ANTERIOR A DATA DO ATENDIMENTO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Autorização / Solicitação',1407,'SERVIÇO SOLICITADO NÃO POSSUI COBERTURA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Autorização / Solicitação',1408,'QUANTIDADE SERVIÇO SOLICITADA ACIMA DA AUTORIZADA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Autorização / Solicitação',1409,'QUANTIDADE SERVIÇO SOLICITADA ACIMA COBERTA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Autorização / Solicitação',1413,'ACOMODAÇÃO NÃO POSSUI COBERTURA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Autorização / Solicitação',1414,'DATA DE VALIDADE DA GUIA EXPIRADA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Autorização / Solicitação',1415,'PROCEDIMENTO NÃO AUTORIZADO PARA O BENEFICIÁRIO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Autorização / Solicitação',1417,'SOLICITANTE NÃO HABILITADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Autorização / Solicitação',1419,'SERVIÇO SOLICITADO JÁ AUTORIZADO','true','false','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Autorização / Solicitação',1420,'SERVIÇO SOLICITADO FORA DA COBERTURA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Autorização / Solicitação',1422,'ESPECIALIDADE NÃO CADASTRADA PARA O SOLICITANTE','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Autorização / Solicitação',1423,'QUANTIDADE SOLICITADA ACIMA DA QUANTIDADE PERMITIDA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Autorização / Solicitação',1424,'QUANTIDADE AUTORIZADA ACIMA DA QUANTIDADE PERMITIDA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Autorização / Solicitação',1425,'NECESSITA PRÉ-AUTORIZAÇÃO DA ORGANIZAÇÃO MILITAR','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Autorização / Solicitação',1426,'NÃO AUTORIZADO PELA AUDITORIA MÉDICA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Autorização / Solicitação',1427,'NECESSIDADE DE AUDITORIA MÉDICA','true','false','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Autorização / Solicitação',1429,'CBO-S (ESPECIALIDADE) NÃO AUTORIZADO A REALIZAR O SERVIÇO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Autorização / Solicitação',1430,'PROCEDIMENTO ODONTOLÓGICO NÃO AUTORIZADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Autorização / Solicitação',1431,'PROCEDIMENTO NÃO AUTORIZADO NA FACE SOLICITADA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Autorização / Solicitação',1432,'PROCEDIMENTO NÃO AUTORIZADO PARA DENTE/REGIÃO SOLICITADA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Autorização / Solicitação',1433,'PROCEDIMENTO NÃO AUTORIZADO, DENTE AUSENTE','true','false','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Diagnóstico',1501,'TEMPO DE EVOLUÇÃO DA DOENÇA INVÁLIDO','true','false','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Diagnóstico',1502,'TIPO DE DOENÇA INVÁLIDO','true','false','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Diagnóstico',1503,'INDICADOR DE ACIDENTE INVÁLIDO','true','false','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Diagnóstico',1504,'CARÁTER DE INTERNAÇÃO INVÁLIDO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Diagnóstico',1505,'REGIME DA INTERNAÇÃO INVÁLIDO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Diagnóstico',1506,'TIPO DE INTERNAÇÃO INVÁLIDO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Diagnóstico',1507,'URGÊNCIA NÃO APLICÁVEL','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Diagnóstico',1508,'CÓDIGO CID NÃO INFORMADO','true','false','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Diagnóstico',1509,'CÓDIGO CID INVÁLIDO','true','false','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Atendimento',1602,'TIPO DE ATENDIMENTO INVÁLIDO OU NÃO INFORMADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Atendimento',1603,'TIPO DE CONSULTA INVÁLIDO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Atendimento',1604,'TIPO DE SAÍDA INVÁLIDO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Atendimento',1605,'INTERVENÇÃO ANTERIOR A ADMISSÃO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Atendimento',1606,'FINAL DA INTERVENÇÃO ANTERIOR AO INÍCIO DA INTERVENÇÃO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Atendimento',1607,'ALTA HOSPITALAR ANTERIOR AO FINAL DA INTERVENÇÃO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Atendimento',1608,'ALTA ANTERIOR À DATA DE INTERNAÇÃO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Atendimento',1609,'MOTIVO SAÍDA INVÁLIDO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Atendimento',1610,'ÓBITO MULHER INVÁLIDO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Atendimento',1611,'INTERVENÇÃO ANTERIOR A INTERNAÇÃO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Atendimento',1612,'SERVIÇO NÃO PODE SER REALIZADO NO LOCAL ESPECIFICADO','true','false','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Atendimento',1613,'CONSULTA NÃO AUTORIZADA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Atendimento',1614,'SERVIÇO AMBULATORIAL NÃO AUTORIZADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Atendimento',1615,'INTERNAÇÃO NÃO AUTORIZADA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Regra de Valorização',1701,'COBRANÇA FORA DO PRAZO DE VALIDADE','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Regra de Valorização',1702,'COBRANÇA DE PROCEDIMENTO EM DUPLICIDADE','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Regra de Valorização',1703,'HORÁRIO DO ATENDIMENTO NÃO ESTÁ NA FAIXA DE URGÊNCIA/EMERGÊNCIA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Regra de Valorização',1704,'VALOR COBRADO SUPERIOR AO ACORDADO EM PACOTE','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Regra de Valorização',1705,'VALOR APRESENTADO A MAIOR','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Regra de Valorização',1706,'VALOR APRESENTADO A MENOR','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Regra de Valorização',1708,'NÃO EXISTE VALOR PARA O PROCEDIMENTO REALIZADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Regra de Valorização',1709,'FALTA PRESCRIÇÃO MÉDICA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Regra de Valorização',1710,'FALTA VISTO DA ENFERMAGEM','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Regra de Valorização',1711,'PROCEDIMENTO PERTENCE A UM PACOTE ACORDADO E JÁ COBRADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Regra de Valorização',1712,'ASSINATURA DO MÉDICO RESPONSÁVEL PELO EXAME INEXISTENTE','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Regra de Valorização',1713,'FATURAMENTO INVÁLIDO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Regra de Valorização',1714,'VALOR DO SERVIÇO SUPERIOR AO VALOR DE TABELA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Regra de Valorização',1715,'VALOR DO SERVIÇO INFERIOR AO VALOR DE TABELA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Regra de Valorização',1716,'PERCENTUAL DE REDUÇÃO/ACRÉSCIMO FORA DOS VALORES DEFINIDOS EM TABELA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimento',1801,'PROCEDIMENTO INVÁLIDO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimento',1802,'PROCEDIMENTO INCOMPATÍVEL COM O SEXO DO BENEFICIÁRIO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimento',1803,'IDADE DO BENEFICIÁRIO INCOMPATÍVEL COM O PROCEDIMENTO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimento',1804,'NÚMERO DE DIAS LIBERADOS / SESSÕES AUTORIZADAS NÃO INFORMADAS','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimento',1805,'VALOR TOTAL DO PROCEDIMENTO DIFERENTE DO VALOR PROCESSADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimento',1807,'PROCEDIMENTOS MÉDICOS DUPLICADOS','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimento',1808,'PROCEDIMENTO NÃO CONFORME COM CID','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimento',1809,'COBRANÇA DE PROCEDIMENTO NÃO EXECUTADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimento',1810,'COBRANÇA DE PROCEDIMENTO NÃO SOLICITADO PELO MÉDICO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimento',1811,'PROCEDIMENTO SEM REGISTRO DE EXECUÇÃO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimento',1812,'COBRANÇA DE PROCEDIMENTO NÃO CORRELACIONADO AO RELATÓRIO ESPECÍFICO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimento',1813,'COBRANÇA DE PROCEDIMENTO SEM JUSTIFICATIVA PARA REALIZAÇÃO OU COM JUSTIFICATIVA INSUFICIENTE.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimento',1814,'COBRANÇA DE PROCEDIMENTO COM DATA DE AUTORIZAÇÃO POSTERIOR À DO ATENDIMENTO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimento',1815,'PROCEDIMENTO NÃO AUTORIZADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimento',1816,'COBRANÇA DE PROCEDIMENTO EM QUANTIDADE INCOMPATÍVEL COM O PROCEDIMENTO/EVOLUÇÃO CLÍNICA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimento',1817,'COBRANÇA DE PROCEDIMENTO INCLUSO NO PROCEDIMENTO PRINCIPAL','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimento',1818,'COBRANÇA DE PROCEDIMENTO QUE EXIGE AUTORIZAÇÃO PRÉVIA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimento',1819,'COBRANÇA DE PROCEDIMENTO COM HISTÓRIA CLÍNICA/HIPÓTESE DIAGNÓSTICA NÃO COMPATÍVEL','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimento',1820,'COBRANÇA DE PROCEDIMENTO EM QUANTIDADE ACIMA DA MÁXIMA PERMITIDA/AUTORIZADA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimento',1821,'COBRANÇA DE PROCEDIMENTO NÃO COMPATÍVEL COM A IDADE.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimento',1822,'COBRANÇA DE PROCEDIMENTO COM AUSÊNCIA DE RESULTADO OU LAUDO TÉCNICO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimento',1823,'PROCEDIMENTO REALIZADO PELO MESMO PROFISSIONAL, NA MESMA ESPECIALIDADE, NO PRAZO INFERIOR AO ESTIPULADO SEM JUSTIFICATIVA ADEQUADA.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimento',1824,'PROCEDIMENTO COBRADO NÃO CORRESPONDE AO EXAME EXECUTADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimento',1825,'COBRANÇA DE PROCEDIMENTO AMBULATORIAL COM DATA DE AUTORIZAÇÃO POSTERIOR À DO ATENDIMENTO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Diária',1901,'ACOMODAÇÃO INVÁLIDA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Diária',1902,'ACOMODAÇÃO INFORMADA NÃO ESTÁ DE ACORDO COM ACOMODAÇÃO CONTRATADA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Diária',1903,'PERMANÊNCIA HOSPITALAR INCOMPATÍVEL COM A EVOLUÇÃO CLÍNICA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Diária',1904,'PERMANÊNCIA HOSPITALAR INCOMPATÍVEL COM O PROCEDIMENTO AUTORIZADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Diária',1906,'ACOMODAÇÃO NÃO INFORMADA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Diária',1907,'QUANTIDADE UTI NÃO PREVISTA PARA PROCEDIMENTO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Diária',1909,'ACOMODAÇÃO NÃO AUTORIZADA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Diária',1910,'COBRANÇA DE DIÁRIAS EM LOCAIS DE ACOMODAÇÕES DIFERENTES, NO MESMO DIA.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Diária',1911,'PERMANÊNCIA HOSPITALAR PARA INVESTIGAÇÃO INJUSTIFICADA.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Diária',1912,'EVOLUÇÃO CLÍNICA NÃO COMPATÍVEL COM A PERMANÊNCIA EM UTI.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Diária',1913,'CÓDIGO DE DIÁRIA INCOMPATÍVEL COM O LOCAL DE ATENDIMENTO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Diária',1914,'COBRANÇA DE DIÁRIA EM QUANTIDADE INCOMPATÍVEL COM A PERMANÊNCIA HOSPITALAR.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Diária',1915,'MUDANÇA DE ACOMODAÇÃO SEM COMUNICAÇÃO AO PACIENTE, FAMILIAR OU ACOMPANHANTE, OU SEM SOLICITAÇÃO DESTES.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Diária',1916,'COBRANÇA DE DIÁRIAS DE UTI INCOMPATÍVEL COM DIAGNÓSTICO E EVOLUÇÃO CLÍNICA.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Material',2001,'MATERIAL INVÁLIDO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Material',2002,'MATERIAL SEM COBERTURA PARA ATENDIMENTO AMBULATORIAL','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Material',2003,'MATERIAL NÃO ESPECIFICADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Material',2004,'MATERIAL SEM NOTA FISCAL DO FORNECEDOR','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Material',2006,'MATERIAL INFORMADO NÃO COBERTO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Material',2007,'COBRANÇA DE MATERIAL EM QUANTIDADE INCOMPATÍVEL COM A PERMANÊNCIA.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Material',2008,'COBRANÇA DE MATERIAL EM QUANTIDADES INCOMPATÍVEIS COM O PROCEDIMENTO REALIZADO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Material',2009,'QUANTIDADE DE MATERIAL SUPERIOR A QUANTIDADE COBERTA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Material',2010,'COBRANÇA DE MATERIAIS INCLUSOS NAS TAXAS','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Material',2011,'COBRANÇA DE MATERIAL INCLUSO NO PACOTE NEGOCIADO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Material',2012,'COBRANÇA DE MATERIAL INCOMPATÍVEL COM O RELATÓRIO TÉCNICO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Material',2013,'COBRANÇA DE MATERIAL EM PERMANÊNCIA HOSPITALAR NÃO AUTORIZADA.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Material',2014,'COBRANÇA DE MATERIAL NÃO UTILIZADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Medicamento',2102,'MEDICAMENTO SEM COBERTURA PARA ATENDIMENTO AMBULATORIAL','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Medicamento',2103,'MEDICAMENTO NÃO ESPECIFICADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Medicamento',2104,'MEDICAMENTO SEM NOTA FISCAL DO FORNECEDOR','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Medicamento',2106,'MEDICAMENTO INFORMADO NÃO COBERTO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Medicamento',2107,'COBRANÇA DE MEDICAMENTO EM QUANTIDADE INCOMPATÍVEL COM A PERMANÊNCIA.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Medicamento',2108,'COBRANÇA DE MEDICAMENTO EM QUANTIDADES INCOMPATÍVEIS COM O PROCEDIMENTO REALIZADO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Medicamento',2109,'QUANTIDADE DE MEDICAMENTO SUPERIOR A QUANTIDADE COBERTA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Medicamento',2110,'COBRANÇA DE MEDICAMENTO INCLUSOS NAS TAXAS','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Medicamento',2111,'COBRANÇA DE MEDICAMENTO INCLUSO NO PACOTE NEGOCIADO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Medicamento',2112,'COBRANÇA DE MEDICAMENTO INCOMPATÍVEL COM O RELATÓRIO TÉCNICO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Medicamento',2113,'COBRANÇA DE MEDICAMENTO EM PERMANÊNCIA HOSPITALAR NÃO AUTORIZADA.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Medicamento',2114,'COBRANÇA DE MEDICAMENTO NÃO UTILIZADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'OPM',2201,'OPME INVÁLIDO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'OPM',2202,'OPME SEM COBERTURA PARA ATENDIMENTO AMBULATORIAL','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'OPM',2203,'OPME SEM NOTA FISCAL DO FORNECEDOR','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'OPM',2205,'OPME INFORMADO NÃO COBERTO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'OPM',2206,'OPME INFORMADO NÃO AUTORIZADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'OPM',2207,'COBRANÇA DE OPME NÃO UTILIZADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'OPM',2208,'COBRANÇA DE OPME NO ITEM MATERIAL E MEDICAMENTOS.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'OPM',2209,'COBRANÇA DE OPME EM DESACORDO COM RELATÓRIO TÉCNICO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'OPM',2210,'COBRANÇA DE OPME EM QUANTIDADE INCOMPATÍVEL COM O PROCEDIMENTO REALIZADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'OPM',2211,'COBRANÇA DE OPME INCLUSA NO PACOTE','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Gases Medicinais',2301,'GASES MEDICINAIS INVÁLIDOS','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Gases Medicinais',2302,'COBRANÇA DE OXIGENOTERAPIA SEM PRESCRIÇÃO MÉDICA.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Gases Medicinais',2303,'COBRANÇA DE OXIGENOTERAPIA COM QUANTITATIVO DE USO EM DIVERGÊNCIA/PAGO VALOR CORRIGIDO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Gases Medicinais',2304,'COBRANÇA DE OXIGÊNIO INCLUSO NA TAXA DE NEBULIZAÇÃO ESPECIFICADA.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Gases Medicinais',2305,'COBRANÇA DE OXIGENOTERAPIA EM USO PROLONGADO  SEM  JUSTIFICATIVA DE USO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Gases Medicinais',2306,'COBRANÇA DE OXIGENOTERAPIA SEM REGISTRO DE CONTROLE DE USO (ENTRADA E SAÍDA).','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Gases Medicinais',2307,'COBRANÇA DE GASES EM QUANTIDADE SUPERIOR AO PERÍODO DE PERMANÊNCIA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Gases Medicinais',2308,'COBRANÇA DE CO2 NAS CIRURGIAS VIDEOLAPAROSCÓPICAS DURANTE TODA A REALIZAÇÃO DO PROCEDIMENTO (INÍCIO AO FIM).','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Gases Medicinais',2309,'COBRANÇA DE AR COMPRIMIDO SEM REGISTRO NO BOLETIM ANESTÉSICO E DURAÇÃO DE USO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Gases Medicinais',2310,'COBRANÇA DE GASES INCOMPATÍVEL COM O UTILIZADO/ PRESCRITO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Taxas e aluguéis',2401,'TAXA / ALUGUEL INVÁLIDO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Taxas e aluguéis',2402,'COBRANÇA DE TAXA POR USO DE EQUIPAMENTO INCOMPATÍVEL COM O PROCEDIMENTO REALIZADO/USO PREVISTO NO PROCEDIMENTO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Taxas e aluguéis',2403,'COBRANÇA DE TAXA DE USO DE BOMBA DE INFUSÃO EM PACIENTE INTERNADO NA UTI','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Taxas e aluguéis',2404,'COBRANÇA DE OUTRAS TAXAS ASSOCIADAS/INCLUSAS NA COBRANÇA DA TAXA DE SALA PREVISTA.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Taxas e aluguéis',2405,'COBRANÇA DE MAIS DE UMA TAXA DE SALA DE CIRURGIA, POR CONTA DO NÚMERO DE PROCEDIMENTOS REALIZADOS NO MESMO TEMPO CIRÚRGICO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Taxas e aluguéis',2406,'COBRANÇA INDEVIDA DE TAXA DE SALA POR ADMINISTRAÇÃO DE MEDICAMENTOS.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Taxas e aluguéis',2407,'COBRANÇA DE TAXAS, DE SERVIÇOS REALIZADOS EM AMBIENTES INCOMPATÍVEIS COM O USO DE EQUIPAMENTOS.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Taxas e aluguéis',2408,'COBRANÇA DE TAXAS EM QUANTIDADE SUPERIOR AO TEMPO DE PERMANÊNCIA HOSPITALAR','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Taxas e aluguéis',2409,'COBRANÇA DE TAXA DE OBSERVAÇÃO EM PRONTO SOCORRO COM PERMANÊNCIA MENOR QUE O PERÍODO ESTIPULADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Taxas e aluguéis',2410,'COBRANÇA DE TAXA DE OBSERVAÇÃO EM PRONTO SOCORRO SEM O REGISTRO DA PERMANÊNCIA.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Taxas e aluguéis',2411,'COBRANÇA DE TAXA DE SALA DE PRONTO SOCORRO, PARA APLICAÇÃO DE MEDICAMENTOS.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Taxas e aluguéis',2412,'COBRANÇA DE TAXA DE RECUPERAÇÃO ANESTÉSICA NÃO JUSTIFICADA PARA O PROCEDIMENTO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Taxas e aluguéis',2413,'COBRANÇA DE TAXA INCLUSA NO PACOTE NEGOCIADO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Taxas e aluguéis',2414,'COBRANÇA DE TAXA DE EQUIPAMENTO EM CONCOMITÂNCIA COM A COBRANÇA DE TAXA PARA O PROCEDIMENTO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Taxas e aluguéis',2416,'COBRANÇA DE TAXA DE RECUPERAÇÃO ANESTÉSICA PARA PACIENTES COM PÓS-OPERATÓRIO IMEDIATO REALIZADO NA UTI/CTI.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Taxas e aluguéis',2417,'COBRANÇA DE TAXA DE RECUPERAÇÃO ANESTÉSICA SEM A PRESENÇA DO ANESTESISTA.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Taxas e aluguéis',2418,'COBRANÇA DE TAXA DE SALA INCOMPATÍVEL COM O PROCEDIMENTO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Taxas e aluguéis',2419,'COBRANÇA DE TAXA DE OBSERVAÇÃO PARA ATENDIMENTO QUE GEROU UMA INTERNAÇÃO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Taxas e aluguéis',2420,'COBRANÇA DE TAXA DE SALA CIRÚRGICA COM PORTE ANESTÉSICO DIFERENTE DO PROCEDIMENTO AUTORIZADO/REALIZADO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Taxas e aluguéis',2421,'COBRANÇA DE TAXA EM QUANTIDADE INCORRETA.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Taxas e aluguéis',2422,'COBRANÇA DE TAXA POR USO DE EQUIPAMENTO DE USO OBRIGATÓRIO NA SALA DE CIRURGIA, CUJA TAXA DE SALA CIRÚRGICA JÁ INCLUI SEU USO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Taxas e aluguéis',2423,'COBRANÇA DE TAXA DE EQUIPAMENTOS DE USO OBRIGATÓRIO NO LOCAL DE ATENDIMENTO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimentos em Série',2502,'COBRANÇA DE DUAS AVALIAÇÕES FISIOTERÁPICAS','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimentos em Série',2503,'COBRANÇA DE PSICOTERAPIA INDIVIDUAL, QUANDO O APLICADO É A COBRANÇA DE PSICOTERAPIA EM GRUPO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimentos em Série',2504,'QUANTIDADE DE SESSÕES COBRADAS NÃO CONDIZEM COM AS ASSINATURAS NO CONTROLE DE TRATAMENTO SERIADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimentos em Série',2505,'O CÓDIGO COBRADO É DIFERENTE DO CÓDIGO AUTORIZADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimentos em Série',2506,'A QUANTIDADE DE SESSÕES COBRADAS É DIFERENTE DA QUANTIDADE AUTORIZADA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimentos em Série',2507,'O CÓDIGO AUTORIZADO ESTÁ INCOMPATÍVEL COM A PRESCRIÇÃO MÉDICA SOLICITADA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimentos em Série',2508,'COBRANÇA DE SESSÕES SEM O DEVIDO PLANO DE TRATAMENTO E, OU, COM O PRAZO DE PAGAMENTO EXPIRADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimentos em Série',2509,'COBRANÇA DO PROCEDIMENTO SERIADO INCOMPATÍVEL COM O QUADRO CLÍNICO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimentos em Série',2510,'COBRANÇA DO PROCEDIMENTO SERIADO EM NÚMERO DE SESSÕES ACIMA DA QUANTIDADE ESTABELECIDA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimentos em Série',2511,'AUSÊNCIA DE EVOLUÇÃO NO PRONTUÁRIO MÉDICO DO TRATAMENTO SERIADO REALIZADO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimentos em Série',2512,'COBRANÇA DE SESSÕES DE FISIOTERAPIA EM DESACORDO COM AS EVOLUÇÕES DO PRONTUÁRIO MÉDICO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimentos em Série',2513,'COBRANÇA DE TRATAMENTO SERIADO SEM JUSTIFICATIVA CLÍNICA/TÉCNICA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Procedimentos em Série',2516,'QUANTIDADE COBRADA DIFERENTE DA REALIZADA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Honorários',2601,'CODIFICAÇÃO INCORRETA/INADEQUADA DO PROCEDIMENTO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Honorários',2602,'COBRANÇA DE HONORÁRIO INCLUSO NO PROCEDIMENTO PRINCIPAL','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Honorários',2603,'COBRANÇA DE HONORÁRIO SEM REGISTRO DA EFETIVA PARTICIPAÇÃO DO PROFISSIONAL','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Honorários',2604,'PROCEDIMENTO PRINCIPAL NÃO REQUER EQUIPE MÉDICA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Honorários',2605,'NÃO CABE PAGAMENTO DO HONORÁRIO INTEGRAL POR SER A MESMA VIA DE ACESSO CIRÚRGICO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Honorários',2606,'COBRANÇA DO HONORÁRIO EM LOCAL DE ATENDIMENTO INCORRETO (INEXISTENTE).','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Honorários',2607,'COBRANÇA DE HONORÁRIOS EM DUPLICIDADE.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Honorários',2608,'COBRANÇA DE CONSULTA INDEVIDA, QUANDO O PROCEDIMENTO PRINCIPAL JÁ ESTÁ SENDO REMUNERADO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Honorários',2609,'LOCAL DE ATENDIMENTO NÃO INFORMADO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Exames',2701,'PROCEDIMENTO INVÁLIDO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Exames',2702,'COBRANÇA DE EXAME NÃO SOLICITADO PELO MÉDICO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Exames',2703,'EXAME SEM REGISTRO DE EXECUÇÃO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Exames',2704,'COBRANÇA DE EXAME NÃO CORRELACIONADO AO RELATÓRIO ESPECÍFICO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Exames',2705,'COBRANÇA DE PROCEDIMENTO/EXAME SEM JUSTIFICATIVA PARA REALIZAÇÃO OU COM JUSTIFICATIVA INSUFICIENTE.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Exames',2706,'COBRANÇA DE PROCEDIMENTO/EXAME COM DATA DE AUTORIZAÇÃO POSTERIOR À DO ATENDIMENTO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Exames',2707,'EXAME NÃO AUTORIZADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Exames',2708,'COBRANÇA DE EXAME EM QUANTIDADE INCOMPATÍVEL COM O PROCEDIMENTO/EVOLUÇÃO CLÍNICA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Exames',2709,'COBRANÇA DE PROCEDIMENTO INCLUSO NO PROCEDIMENTO PRINCIPAL','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Exames',2710,'COBRANÇA DE EXAME QUE EXIGE AUTORIZAÇÃO PRÉVIA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Exames',2711,'COBRANÇA DE EXAME COM HISTÓRIA CLÍNICA/HIPÓTESE DIAGNÓSTICA NÃO COMPATÍVEL','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Exames',2712,'COBRANÇA DE EXAME EM QUANTIDADE ACIMA DA MÁXIMA PERMITIDA/AUTORIZADA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Exames',2713,'COBRANÇA DE EXAME NÃO COMPATÍVEL COM A IDADE.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Exames',2714,'COBRANÇA DE EXAME COM AUSÊNCIA DE RESULTADO OU LAUDO TÉCNICO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Exames',2715,'EXAME REALIZADO PELO MESMO PROFISSIONAL, NA MESMA ESPECIALIDADE, NO PRAZO INFERIOR AO ESTIPULADO SEM JUSTIFICATIVA ADEQUADA.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Exames',2716,'EXAME COBRADO NÃO CORRESPONDE AO EXAME EXECUTADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Exames',2717,'COBRANÇA DE EXAME AMBULATORIAL COM DATA DE AUTORIZAÇÃO POSTERIOR À DO ATENDIMENTO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Exames',2718,'EXAMES NÃO JUSTIFICAM CARÁTER DE URGÊNCIA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Pacotes',2801,'PACOTE INVÁLIDO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Pacotes',2802,'PACOTE INCOMPATÍVEL COM O SEXO DO BENEFICIÁRIO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Pacotes',2803,'IDADE DO BENEFICIÁRIO INCOMPATÍVEL COM O PACOTE','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Pacotes',2804,'VALOR TOTAL DO PACOTE DIFERENTE DO VALOR PROCESSADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Pacotes',2806,'COBRANÇA DE PACOTE NÃO EXECUTADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Pacotes',2807,'COBRANÇA DE PACOTE NÃO SOLICITADO PELO MÉDICO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Pacotes',2808,'PACOTE SEM REGISTRO DE EXECUÇÃO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Pacotes',2809,'COBRANÇA DE PACOTE NÃO CORRELACIONADO AO RELATÓRIO ESPECÍFICO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Pacotes',2810,'COBRANÇA DE PACOTE SEM JUSTIFICATIVA PARA REALIZAÇÃO OU COM JUSTIFICATIVA INSUFICIENTE.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Pacotes',2811,'COBRANÇA DE PACOTE COM DATA DE AUTORIZAÇÃO POSTERIOR À DO ATENDIMENTO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Pacotes',2812,'PACOTE NÃO AUTORIZADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Pacotes',2813,'COBRANÇA DE PACOTE EM QUANTIDADE INCOMPATÍVEL COM O PROCEDIMENTO/EVOLUÇÃO CLÍNICA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Pacotes',2815,'COBRANÇA DO PACOTE EXIGE AUTORIZAÇÃO PRÉVIA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Pacotes',2816,'COBRANÇA DE PACOTE COM HISTÓRIA CLÍNICA/HIPÓTESE DIAGNÓSTICA NÃO COMPATÍVEL','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Pacotes',2817,'COBRANÇA DE PACOTE EM QUANTIDADE ACIMA DA MÁXIMA PERMITIDA/AUTORIZADA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Pacotes',2818,'COBRANÇA DE PACOTE NÃO COMPATÍVEL COM A IDADE.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Pacotes',2819,'COBRANÇA DE PACOTE COM AUSÊNCIA DE RESULTADO OU LAUDO TÉCNICO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Pacotes',2820,'PACOTE REALIZADO PELO MESMO PROFISSIONAL, NA MESMA ESPECIALIDADE, NO PRAZO INFERIOR AO ESTIPULADO SEM JUSTIFICATIVA ADEQUADA.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Pacotes',2821,'PACOTE COBRADO NÃO CORRESPONDE AO EXAME EXECUTADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Pacotes',2822,'COBRANÇA DE PACOTE AMBULATORIAL COM DATA DE AUTORIZAÇÃO POSTERIOR À DO ATENDIMENTO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Revisão de glosa',2901,'REVISÃO DE GLOSA INVÁLIDA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Revisão de glosa',2902,'GLOSA MANTIDA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Revisão de glosa',2903,'PEDIDO DE REVISÃO SEM JUSTIFICATIVA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Revisão de glosa',2904,'MAIS DE UM RECURSO DE GLOSA PARA A MESMA GUIA/PROTOCOLO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Revisão de glosa',2905,'A GUIA NÃO É DE REVISÃO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Revisão de glosa',2906,'NÚMERO DA GUIA INVÁLIDO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3001,'PROCEDIMENTO ODONTOLÓGICO INVÁLIDO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3002,'COBRANÇA DE PROCEDIMENTO ODONTOLÓGICO QUE EXIGE AUTORIZAÇÃO PRÉVIA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3003,'IDADE DO BENEFICIÁRIO INCOMPATÍVEL COM O PROCEDIMENTO ODONTOLÓGICO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3004,'COBRANÇA DE PROCEDIMENTO ODONTOLÓGICO EM QUANTIDADE ACIMA DA MÁXIMA PERMITIDA/AUTORIZADA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3005,'VALOR TOTAL DO PROCEDIMENTO DIFERENTE DO VALOR PROCESSADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3007,'PROCEDIMENTOS ODONTOLÓGICOS DUPLICADOS','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3008,'COBRANÇA DE PROCEDIMENTO ODONTOLÓGICO INCLUSO NO PROCEDIMENTO PRINCIPAL','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3009,'COBRANÇA DE PROCEDIMENTO ODONTOLÓGICO NÃO EXECUTADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3010,'COBRANÇA DE PROCEDIMENTO NÃO SOLICITADO PELO CIRURGIÃO-DENTISTA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3011,'PROCEDIMENTO ODONTOLÓGICO SEM REGISTRO DE EXECUÇÃO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3012,'COBRANÇA DE PROCEDIMENTO ODONTOLÓGICO NÃO CORRELACIONADO AO RELATÓRIO ESPECÍFICO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3013,'COBRANÇA DE PROCEDIMENTO ODONTOLÓGICO SEM JUSTIFICATIVA PARA REALIZAÇÃO OU COM JUSTIFICATIVA INSUFICIENTE.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3014,'COBRANÇA DE PROCEDIMENTO ODONTOLÓGICO COM DATA DE AUTORIZAÇÃO POSTERIOR À DO ATENDIMENTO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3015,'COBRANÇA DE PROCEDIMENTO ODONTOLÓGICO COM AUSÊNCIA DE RESULTADO OU LAUDO TÉCNICO.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3016,'PROCEDIMENTO ODONTOLÓGICO REALIZADO PELO MESMO PROFISSIONAL, NA MESMA ESPECIALIDADE, NO PRAZO INFERIOR AO ESTIPULADO SEM JUSTIFICATIVA ADEQUADA.','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3017,'PROCEDIMENTO COBRADO NÃO CORRESPONDE A PERÍCIA (ESPECIFICAR).','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3018,'EVENTO GLOSADO POR AUDITORIA (ESPECIFICAR)','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3019,'EVENTO SOB ANÁLISE TÉCNICA, AGUARDANDO LIBERAÇÃO DE CONFIRMAÇÃO PARA POSTERIOR PAGAMENTO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3020,'CONFORME DOCUMENTAÇÃO RADIOGRÁFICA ENVIADA, EVENTO REALIZADO INADEQUADAMENTE','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3021,'FALHA EM INFORMAÇÃO DE DADOS DE ARCADAS/HEMI-ARCOS','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3022,'FALHA EM INFORMAÇÃO DE DADOS DE DENTE INICIAL E/OU FINAL','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3023,'FALHA EM INFORMAÇÃO DE DADOS DE FACES DOS DENTES','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3024,'EVENTO SÓ POSSÍVEL EM DENTES DECÍDUOS','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3025,'EVENTO SÓ POSSÍVEL EM DENTES PERMANENTES','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3026,'ERRO NAS INFORMAÇÕES DE ORDEM DOS DENTES INICIAL E FINAL','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3027,'DESACORDO ENTRE O TIPO DE DENTE E O NÚMERO DE CANAIS SOLICITADOS','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3028,'EVENTO RESTRITO À ESPECIALISTAS','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3029,'EVENTO NÃO INDICADO PELA AUDITORIA INICIAL','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3030,'AUDITORIA FINAL CONSTA QUE A RESTAURAÇÃO FOI REALIZADA EM OUTRO MATERIAL','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3031,'RADIOGRAFIA FORA DOS PADRÕES TÉCNICOS','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3032,'INTERVALO DA ÚLTIMA MPP INFERIOR A TRÊS MESES','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3033,'INTERVALO DA ÚLTIMA MPP INFERIOR A QUATRO MESES','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3034,'JUSTIFICATIVA TECNICAMENTE NÃO SATISFATÓRIA','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3037,'PROCEDIMENTO COBRADO NÃO É IGUAL AO EXECUTADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3038,'RADIOGRAFIA INICIAL INCONGRUENTE COM A RADIOGRAFIA FINAL','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3039,'RADIOGRAFIA NÃO CORRESPONDE AO PROCEDIMENTO COBRADO','true','true','true');
insert into sch_sisauc.motivo values ((select nextval('sch_sisauc.motivo_id_seq')),'Odontologia',3040,'GLOSA TÉCNICA (ESPECIFICAR DETALHADAMENTE)','true','true','true');
