insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'81000030','Consulta Odontológica','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'81000294','Levantamento Radiográfico (Exame Radiodôntico)','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'81000324','Radiografia Ântero-posterior','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'81000510','Tomografia computadorizada por feixe cônico - cone beam','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'81000278','Fotografia (por foto)','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'81000308','Modelos Ortodônticos','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'81000340','Radiografia da articulação temporo mandibular - ATM','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'81000367','Radiografia da mão e punho – carpal','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'81000375','Radiografia Interproximal – Bite-Wing','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'81000383','Radiografia Oclusal','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'81000405','Radiografia Panorâmica de mandíbula / maxila (ortopantomografia)','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'81000421','Radiografia Periapical','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'81000430','Radiografia Póstero-anterior','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'81000456','Slide (por slide)','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'81000472','Telerradiografia','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'81000480','Telerradiografia com Traçado Cefalométrico','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'81000529','Tomografia Convencional – Linear ou Multi-Direcional','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'84000090','Aplicação Tópica de Flúor','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'84000163','Controle de Biofilme (Placa Bacteriana)','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'84000198','Profilaxia – Polimento Coronário','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'84000201','Remineralização','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'83000046','Coroa de Aço em dente decíduo','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'83000089','Exodontia de Decíduos','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'83000097','Mantenedor de Espaço Fixo','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'83000100','Mantenedor de Espaço Removível','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'83000127','Pulpotomia em dente decíduo','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'83000135','Restauração Atraumática em dente decíduo','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'83000151','Tratamento Endodôntico em dente decíduo','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'84000031','Aplicação de Cariostático','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'84000058','Aplicação de Selante – Técnica Invasiva','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'84000074','Aplicação de Selante de Fóssulas e Fissuras','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'84000112','Aplicação Tópica de Verniz Fluoretado','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85100064','Faceta Direta em Resina Fotopolimerizável','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85100099','Restauração de Amálgama – 1 face','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85100102','Restauração de Amálgama – 2 faces','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85100110','Restauração de Amálgama – 3 faces','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85100129','Restauração de Amálgama – 4 faces','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85100137','Restauração em Ionômero de vidro 1 face','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85100145','Restauração em Ionômero de Vidro 2 faces','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85100188','Restauração em resina (indireta) - Onlay','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85100196','Restauração de Resina Fotopolimerizável – 1 faces','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85100200','Restauração de Resina Fotopolimerizável – 2 faces','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85100218','Restauração de Resina Fotopolimerizável – 3  faces','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85100226','Restauração de Resina Fotopolimerizável – 4 faces','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85200085','Restauração temporária / tratamento expectante','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400025','Ajuste Oclusal por Desgaste Seletivo','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400211','Núcleo de Preenchimento','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85100048','Colagem de fragmentos dentários','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85100153','Restauração em ionômero de vidro - 3 faces','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85100161','Restauração em ionômero de vidro - 4 faces','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85100013','Capeamento Pulpar direto','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85200034','Pulpectomia','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85200042','Pulpotomia','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85200077','Remoção de Núcleo Intrarradicular','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85200093','Retratamento Endodôntico Birradicular','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85200107','Retratamento Endodôntico Multirradicular','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85200115','Retratamento Endodôntico Unirradicular','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85200123','Tratamento de Perfuração Endodôntica','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85200131','Tratamento Endodôntico de Dente com Rizogênese Incompleta','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85200140','Tratamento Endodôntico Birradicular','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85200158','Tratamento Endodôntico Multirradicular','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85200166','Tratamento Endodôntico Unirradicular','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000050','Amputação Radicular c/ Obturação Retrógrada','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000069','Amputação Radicular s/ Obturação Retrógrada','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000212','Aumento de coroa clínica','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000336','Cirurgia odontológica a retalho','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000417','Cirurgia Periodontal a Retalho','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000557','Cunha Proximal','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000646','Enxerto conjuntivo subepitelial','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000662','Enxerto Gengival Livre','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000689','Enxerto Pediculado','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000921','Gengivectomia por segmento','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000948','Gengivoplastia','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82001073','Odonto-Secção','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85300012','Dessensibilização Dentária','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85300020','Imobilização dentária em dentes','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85300039','Raspagem Sub-Gengival / Alisamento Radicular','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85300047','Raspagem Supra-Gengival','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85300055','Remoção dos  Fatores de Retenção do Biofilme Dental  (Placa Bacteriana)','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85300063','Tratamento de Abscesso Periodontal Agudo','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400033','Conserto em prótese parcial removível','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400050','Conserto em prótese total','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400076','Coroa Provisória com Pino','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400084','Coroa Provisória sem Pino','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400092','Coroa Total Acrílica Prensada','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400106','Coroa Total em Cerâmica Pura','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400114','Coroa Total em Cerômero','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400149','Coroa Total Metálica','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400157','Coroa Total Metalo-Cerâmica','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400165','Coroa Total Metaloplástica - Cerômero','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400181','Faceta em Cerâmica Pura','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400203','Guia cirúrgico para prótese total imediata','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400220','Núcleo Metálico Fundido','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400246','Órtese Miorrelaxante (Placa Oclusal Estabilizadora)','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400254','Órtese reposicionadora (Placa Oclusal Reposicionadora)','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400300','Prótese Fixa Adesiva Indireta Metalo-Cerâmica (até 3 elementos)','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400319','Prótese Fixa Adesiva Indireta Metalo-Plástica (até 3 elementos)','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400335','Prótese Parcial Fixa em Metalo Cerâmica (por elemento)','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400343','Prótese Parcial Fixa em Metalo Plástica (pro elemento)','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400378','Prótese Parcial Removível com Encaixes de Precisão ou de Semi Precisão','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400386','Prótese Parcial Removível com Grampos Bilateral','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400394','Prótese Parcial Removível Provisória em Acrílico com ou sem Grampos','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400408','Prótese Total','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400416','Prótese Total Imediata','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400424','Prótese Total Incolor (caracterizada)','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400483','Reembasamento de Prótese Total ou Parcial – imediato (em consultório)','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400491','Reembasamento de Prótese Total ou Parcial – mediato (em laboratório)','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400521','Restauração em cerâmica pura - onlay','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400530','Restauração em cerômero - Onlay','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'85400556','Restauração Metálica Fundida','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000034','Alveoloplastia','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000077','Apicetomia Birradiculares com Obturação Retrógrada','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000085','Apicetomia Birradiculares sem Obturação Retrógrada','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000158','Apicetomia Multirradiculares com Obturação Retrógrada','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000166','Apicetomia Multirradiculares sem Obturação Retrógrada','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000174','Apicetomia Unirradiculares com Obturação Retrógrada','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000182','Apicetomia Unirradiculares sem Obturação Retrógrada','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000190','Aprofundamento/aumento de vestíbulo','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000239','Biópsia de Boca','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000255','Biópsia de Lábio','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000263','Biópsia de Língua','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000271','Biópsia de Mandíbula','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000280','Biópsia de Maxila','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000298','Bridectomia','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000360','Cirurgia para tórus mandibular - bilateral','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000387','Cirurgia para tórus mandibular - unilateral','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000395','Cirurgia para tórus palatino','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000468','Controle de hemorragia com aplicação de agente hemostático em região buco-maxilo-facial','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000484','Controle de hemorragia sem aplicação de agente hemostático em região buco-maxilo-facial','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000778','Exérese ou Excisão de Cálculo Salivar','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000786','Exérese ou Excisão de Cistos Odontológicos','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000794','Exérese ou Excisão de Mucocele','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000808','Exérese ou excisão de rânula','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000816','Exodontia a Retalho','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000859','Exodontia de Raiz Residual','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000875','Exodontia Simples de Permanente','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000883','Frenulectomia Labial','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82000891','Frenulectomia Lingual','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82001022','Incisão e Drenagem Extra-Oral de Abscesso, Hematoma e/ou Flegmão da Região Buco-Maxilo-Facial','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82001154','Reconstrução de Sulco Gengivo-Labial','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82001251','Reimplante dentário com contenção','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82001286','Remoção de Dentes Inclusos / Impactados','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82001367','Remoção de Odontoma','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82001391','Retirada de corpo estranho oroantral ou oronasal da região buco-maxilo-facial','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82001502','Tracionamento cirúrgico com finalidade ortodôntica','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82001510','Sutura de ferida em região buco-maxilo-facial','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82001510','Tratamento cirúrgico das fístulas buco sinusal','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82001545','Tratamento Cirúrgico de Bridas Constritivas da Região Buco-Maxilo-Facial','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82001596','Tratamento Cirúrgico de Tumores Benignos de Tecidos Osseos/Cartinagilosos na Região Buco-Maxilo-Facial-Osteoma','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82001650','Tratamento de Alveolite','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82001707','Ulectomia','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82001715','Ulotomia','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'87000164','Sedação consciente com óxido nitroso e oxigênio em pacientes com necessidades especiais em odontologia','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'88000133','Biópsia de Glândula Salivar','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'82001294','Remoção de dentes semi-inclusos / impactados','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000047','Aparelho de Thurow','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000055','Aparelho Extra-Bucal','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000098','Aparelho Ortodôntico Fixo metálico por arcada','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000110','Aparelho ortodôntico fixo metálico parcial','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000128','Aparelho Removível com Alças Bionator Invertida ou de Escheler','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000144','Arco Lingual','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000152','Barra Transpalatina Fixa','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000160','Barra Transpalatina Removível','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000179','Bionator de Balters','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000195','Botão de Nance Fixo Superior','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000209','Contenção Fixa – por Arcada','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000225','Disjuntor Palatino – Hyrax','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000233','Disjuntor Palatino – Macnamara','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000250','Distalizador de Hilgers','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000276','Distalizador pendulo /pendex','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000284','Distalizador tipo Jones Jig','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000314','Grade Palatina Fixa','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000322','Grade Palatina Removível','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000330','Herbst Encapsulado','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000381','Máscara Facial – Delaire e Tração Reserva','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000390','Mentoneira','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000403','Modelador Elástico de Bimler','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000411','Monobloco','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000438','Pistas Diretas de Planas','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000462','Placa Hawley','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000470','Placa Hawley – com Torno Expansor','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000519','Placa Dupla de Sanders','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000535','Placa Lábio-Ativa (Bumper)','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000551','Plano Inclinado','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000560','Quadrihélice','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'86000578','Regulador de função Frankel','TRS');