insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60024801','ALUGUEL/TAXA DE APARELHO DE RADIOFREQUÊNCIA, POR USO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60024070','TAXA DE APARELHO / BOMBA DE CIRCULAÇÃO EXTRACORPÓREA, POR USO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60024151','ALUGUELTAXA DE APARELHO / EQUIPAMENTO PARA ARTROSCOPIA PARA CIRURGIA, POR USO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60025018','ALUGUEL / TAXA DE APARELHO PARA TRAÇÃO CRANEANA, POR DIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60025034','TAXA DE INCUBADORA, POR HORA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60025166','ALUGUEL/TAXA DE ASPIRADOR CIRÚRGICO, POR USO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60025204','ALUGUEL/TAXA DE ASPIRADOR ELÉTRICO, POR USO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60025220','TAXA DE ASPIRADOR SUCÇÃO CONTÍNUA, POR DIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60025239','ALUGUEL/TAXA DE ASPIRADOR ULTRA-SÔNICO, POR USO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60025298','BALÃO INTRA AÓRTICO POR DIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60025336','TAXA DE BERÇO AQUECIDO, POR DIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60025387','BERÇO PARA FOTOTERAPIA, POR DIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60025492','ALUGUEL/TAXA DE BISTURI  BIPOLAR, POR USO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60025565','ALUGUEL/TAXA DE BISTURI ELÉTRICO MONOPOLAR, POR USO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60025573','ALUGUEL/TAXA DE BISTURI ULTRASSÔNICO, POR USO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60025662','BOMBA DE INFUSÃO, POR DIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60025697','BOMBA DE SERINGA, POR DIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60025964','TAXA DE CADEIRA DE RODAS, POR DIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60025972','TAXA DE CADEIRA HIGIÊNICA, POR DIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60026154','TAXA DE MARCA PASSO PROVISÓRIO/TEMPORARIO TRANSCUTÂNEO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60026162','CAMA/COLCHÃO/GRADE (ELETRICA PADRÃO)','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60026170','CAMA/COLCHAO/GRADE (MANUAL PADRAO)','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60026308','TAXA DE HALO CRANEANO, POR USO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60026332','ALUGUEL / TAXA DE COLCHÃO DE AR, POR DIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60026391','TAXA DE CONCENTRADOR DE OXIGÊNIO, POR DIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60026413','ALUGUEL / TAXA DE DERMÁTOMO ELÉTRICO, POR USO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60026421','ALUGUEL / TAXA DE DESFIBRILADOR (CARDIOVERSÃO), POR USO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60026570','ALUGUEL / TAXA DE ELETROCHOQUE, POR USO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60025093','ALUGUEL / TAXA DE APARELHO TILLAUX TRANCUTÃNEA, POR DIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60027118','TAXA DE INCUBADORA, POR DIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60027134','TAXA POR USO/SESSÃO INCUBADORA DE  TRANSPORTE SEM OXIGÊNIO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60027142','TAXA POR USO/SESSÃO DE INCUBADORA DE TRANSPORTE COM OXIGÊNIO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60027169','ALUGUEL /  TAXA DE INTENSIFICADOR DE IMAGEM, POR USO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60027363','ALUGUEL / TAXA DE MICROSCÓPIO CIRÚRGICO DE FIBRA ÓTICA, POR USO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60027428','ALUGUEL / TAXA DE MICROSCÓPIO CIRÚRGICO, POR USO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60027495','ALUGUEL / TAXA DE NEURONAVEGADOR, POR USO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60027630','ALUGUEL/TAXA DE RAIOS X PORTÁTIL, POR USO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60027738','TAXA DE RESPIRADOR BIPAP / CPAP, POR DIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60027754','RESPIRADOR MICRO PROCESSADO, POR DIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60027762','RESPIRADOR MICRO PROCESSADO, POR HORA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60027770','RESPIRADOR NEONATAL, POR DIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60027789','RESPIRADOR NEONATAL, POR HORA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60028955','TAXA DE CARRO ANESTÉSICO, POR USO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60029188','TAXA DE MONITOR / MONITORIZAÇÃO  CARDÍACO / ECG, POR DIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60029340','TAXA DE MONITOR / MONITORIZAÇÃO  FETAL, POR DIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60029501','TAXA DE MONITOR / MONITORIZAÇÃO  INTRA CRANIANO, POR DIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60030313','TAXA DE MONITOR / MONITORIZAÇÃO DE CAPNÓGRAFO, POR DIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60030631','TAXA DE MONITOR / MONITORIZAÇÃO DE DÉBITO CARDÍACO, POR DIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60031433','TAXA DE MONITOR / MONITORIZAÇÃO DE OXICAPNÓGRAFO, POR DIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60031760','TAXA DE MONITOR / MONITORIZAÇÃO DE OXÍMETRO, POR DIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60031921','TAXA DE MONITOR / MONITORIZAÇÃO DE PA INVASIVA, POR DIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60032081','TAXA DE MONITOR / MONITORIZAÇÃO DE PA NÃO INVASIVA, POR DIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60032723','TAXA DE MONITOR / MONITORIZAÇÃO DE PVC, POR DIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60032880','TAXA DE MONITOR / MONITORIZAÇÃO DE SWAN GANZ, POR DIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60033916','TAXA DE USO DE CRANIÓTOMO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60034483','TAXA DE USO DO CILINDRO DE OXIGENIO PORTÁTIL - BALA GRANDE, EM DOMICÍLIO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60034491','TAXA DE USO DO CILINDRO DE OXIGENIO PORTÁTIL - BALA PEQUENA, EM DOMICÍLIO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60029102','TAXA DE MICROCÓSPIO NEUROLÓGICO DE FIBRA ÓTICA, POR USO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60027711','RESPIRADOR A VOLUME, POR DIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60031808','TAXA DE MONITOR / MONITORIZAÇÃO DE OXÍMETRO, POR HORA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60027533','ALUGUEL/TAXA DE PERFURADOR ELÉTRICO, POR USO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60027940','ALUGUEL / TAXA DE SERRA DE GESSO, POR USO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60030267','TAXA DE MONITOR / MONITORIZAÇÃO DE BIS / SEDAÇÃO E ANESTESIA, POR USO/SESSÃO, NO CENTRO CIRÚRGICO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60027975','ALUGUEL / TAXA DE SERRA PARA OSSO, POR USO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60027320','ALUGUEL / TAXA DE MÁQUINA DE CARDIOPLEGIA, POR USO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60026383','TAXA DE COLCHÃO TÉRMICO, POR DIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60028394','GÁS CARBÔNICO, POR HORA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60028521','NITROGÊNIO, POR HORA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60028564','ÓXIDO NÍTRICO, POR HORA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60028572','ÓXIDO NITROSO, POR HORA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60034122','AR COMPRIMIDO, POR HORA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'600XXXXX','OXIGÊNIO, VAZÃO DE 3 LITROS/MIN, POR HORA (CORRIDA OU SUBSEQUENTE)','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'600XXXXX','OXIGÊNIO, VAZÃO DE 6 LITROS/MIN, POR HORA (CORRIDA OU SUBSEQUENTE)','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'600XXXXX','OXIGÊNIO, VAZÃO DE 8 LITROS/MIN, POR HORA (CORRIDA OU SUBSEQUENTE)','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'600XXXXX','OXIGÊNIO, VAZÃO DE 9 LITROS/MIN, POR HORA (CORRIDA OU SUBSEQUENTE)','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'600XXXXX','OXIGÊNIO, VAZÃO DE 10 LITROS/MIN, POR HORA (CORRIDA OU SUBSEQUENTE)','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'600XXXXX','OXIGÊNIO, VAZÃO DE 18 LITROS/MIN, POR HORA (CORRIDA OU SUBSEQUENTE)','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60000473','DIÁRIA DE ACOMPANHANTE SOMENTE COM CAFÉ DA MANHÃ','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60000848','DIÁRIA DE  QUARTO COM ALOJAMENTO CONJUNTO COM BANHEIRO PRIVATIVO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60001046','DIÁRIA DE  UTI CORONARIANA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60034424','DIÁRIA DE HOSPITAL DIA, INDEPENDENTE DE ACOMODAÇÃO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60000619','DIÁRIA DE  BERÇÁRIO NORMAL','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60000805','DIÁRIA DE  QUARTO COLETIVO DE 2 LEITOS COM BANHEIRO PRIVATIVO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60000651','DIÁRIA DE  APARTAMENTO STANDARD','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60001054','DIÁRIA DE  UTI INFANTIL/PEDIÁTRICA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60001062','DIÁRIA DE  UTI NEONATAL','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60001038','DIÁRIA DE  UTI ADULTO GERAL','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60001011','DIÁRIA DE  UNIDADE INTERMEDIÁRIA GERAL','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60022817','TAXA DE NECROTÉRIO, POR USO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60022965','TAXA DE SALA/SESSÃO DE INALAÇÃO/NEBULIZAÇÃO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60023082','TAXA POR USO/SESSÃO DE SALA CIRÚRGICA, PEQUENA CIRURGIA AMBULATORIAL','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60023090','TAXA DE SALA CIRÚRGICA, PORTE ANESTÉSICO 0','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60023104','TAXA DE SALA CIRÚRGICA, PORTE ANESTÉSICO 1','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60023112','TAXA DE SALA CIRÚRGICA, PORTE ANESTÉSICO 2','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60023120','TAXA DE SALA CIRÚRGICA, PORTE ANESTÉSICO 3','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60023139','TAXA DE SALA CIRÚRGICA, PORTE ANESTÉSICO 4','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60023147','TAXA DE SALA CIRÚRGICA, PORTE ANESTÉSICO 5','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60023155','TAXA DE SALA CIRÚRGICA, PORTE ANESTÉSICO 6','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60023163','TAXA DE SALA CIRÚRGICA, PORTE ANESTÉSICO 7','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60023171','TAXA DE SALA CIRÚRGICA, PORTE ANESTÉSICO 8','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60023180','TAXA DE SALA CIRÚRGICA, RECUPERAÇÃO PÓS ANESTÉSICA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60023228','TAXA POR USO/SESSÃO DE SALA DE BRONCOSCOPIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60023244','TAXA POR USO/SESSÃO DE SALA DE COLONOSCOPIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60023287','TAXA POR USO/SESSÃO DE SALA DE ENDOSCOPIA DIGESTIVA ALTA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60023295','TAXA POR USO/SESSÃO DE SALA DE ENDOSCOPIA GINECOLÓGICA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60023309','TAXA POR USO/SESSÃO DE SALA DE ENDOSCOPIA UROLÓGICA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60023317','TAXA POR USO/SESSÃO DE SALA DE HEMODIÁLISE','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60023325','TAXA POR USO/SESSÃO DE SALA DE HEMODINÂMICA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60023406','TAXA POR USO/SESSÃO DE SALA DE QUIMIOTERAPIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60023414','TAXA POR USO/SESSÃO DE SALA DE RADIOLOGIA INTERVENCIONISTA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60033681','TAXA DE SALA DE OBSERVAÇÃO, ATÉ 6 HORAS','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60023236','TAXA POR USO/SESSÃO DE SALA DE COLOCAÇÃO/RETIRADA DE GESSO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60023708','UTILIZAÇÃO DE BANDEJA  DE ASSEPSIA / ANTI-SEPSIA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60023740','UTILIZAÇÃO DE BANDEJA  DE PEQUENA CIRURGIA FORA DO CENTRO CIRÚRGICO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60023821','UTILIZAÇÃO DE BANDEJA  PARA ANESTESIA GERAL','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60023880','UTILIZAÇÃO DE BANDEJA  PARA PUNÇÃO EM GERAL','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60023996','UTILIZAÇÃO DE BANDEJA PARA SONDAGEM/CATETERISMO VESICAL','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60026022','ALUGUEL/TAXA CAIXA / INSTRUMENTAL DE INSTRUMENTAL BASICO, POR USO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60023899','UTILIZAÇÃO DE BANDEJA  PARA RETIRADA DE PONTOS','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60023767','UTILIZAÇÃO DE BANDEJA  DE SUTURA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60023732','UTILIZAÇÃO DE BANDEJA  DE ENTUBAÇÃO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60018798','REMOÇÃO EM AMBULÂNCIA NEONATAL, COM MÉDICO E ENFERMAGEM, PARA TRANSFERÊNCIA, NO MUNICÍPIO, ESPERA / HORA PARADA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60018810','REMOÇÃO EM AMBULÂNCIA NEONATAL, COM MÉDICO E ENFERMAGEM, PARA TRANSFERÊNCIA, NO MUNICÍPIO, POR KM','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60019271','REMOÇÃO EM AMBULÂNCIA SIMPLES ADULTO, COM MÉDICO E ENFERMAGEM, PARA TRANSFERÊNCIA, NO MUNICÍPIO, ESPERA / HORA PARADA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60019298','REMOÇÃO EM AMBULÂNCIA SIMPLES ADULTO, COM MÉDICO E ENFERMAGEM, PARA TRANSFERÊNCIA, NO MUNICÍPIO, POR KM','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60020954','REMOÇÃO EM AMBULÂNCIA UTI ADULTO, COM MÉDICO E ENFERMAGEM, PARA TRANSFERÊNCIA, NO MUNICÍPIO, ESPERA / HORA PARADA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60020970','REMOÇÃO EM AMBULÂNCIA UTI ADULTO, COM MÉDICO E ENFERMAGEM, PARA TRANSFERÊNCIA, NO MUNICÍPIO, POR KM','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60020237','REMOÇÃO EM AMBULÂNCIA SIMPLES PEDIÁTRICA, COM MÉDICO E ENFERMAGEM, PARA TRANSFERÊNCIA, NO MUNICÍPIO, ESPERA / HORA PARADA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60020253','REMOÇÃO EM AMBULÂNCIA SIMPLES PEDIÁTRICA, COM MÉDICO E ENFERMAGEM, PARA TRANSFERÊNCIA, NO MUNICÍPIO, POR KM','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60021195','REMOÇÃO EM AMBULÂNCIA UTI PEDIÁTRICA, COM MÉDICO E ENFERMAGEM, PARA TRANSFERÊNCIA, NO MUNICÍPIO, ESPERA / HORA PARADA','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60021217','REMOÇÃO EM AMBULÂNCIA UTI PEDIÁTRICA, COM MÉDICO E ENFERMAGEM, PARA TRANSFERÊNCIA, NO MUNICÍPIO, POR KM','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60015160','ALIMENTAÇÃO ENTERAL, PREPARO, FORA DA UTI/SEMI-UTI E DO CENTRO CIRÚRGICO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60015179','ALIMENTAÇÃO ENTERAL, PREPARO, NA UTI/SEMI-UTI','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60015225','ALIMENTAÇÃO PARENTERAL, PREPARO, FORA DA UTI/SEMI-UTI E DO CENTRO CIRÚRGICO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60018593','TAXA DE DESINFECÇÃO/ESTERILIZAÇÃO DE INSTRUMENTAL CIRÚRGICO, POR USO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60018623','TAXA DE PREPARO DE QUIMIOTERÁPICOS, POR USO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60034009','TAXA POR UNIDADE DE CURATIVO GRANDE','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60034017','TAXA POR UNIDADE DE CURATIVO MÉDIO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60034025','TAXA POR UNIDADE DE CURATIVO PEQUENO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60034459','TAXA DE AUXILIAR/TÉCNICO DE ENFERMAGEM NO DOMICÍLIO ATÉ 6 HORAS','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60034467','TAXA DE AUXILIAR/TÉCNICO DE ENFERMAGEM NO DOMICÍLIO ATÉ 12 HORAS','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60034475','TAXA DE AUXILIAR/TÉCNICO DE ENFERMAGEM NO DOMICÍLIO ATÉ 24 HORAS','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60006730','MACRONEBULIZAÇÃO COM AR COMPRIMIDO, VAZÃO DE 5 LITROS/MIN, POR DIA (CORRIDO OU SUBSEQUENTE), FORA DA UTI/SEMI-UTI E DO CENTRO CIRÚRGICO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60006749','MACRONEBULIZAÇÃO COM AR COMPRIMIDO, VAZÃO DE 5 LITROS/MIN, POR DIA (CORRIDO OU SUBSEQUENTE), NA UTI / SEMI-UTI','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60022256','TAXA DE IMOBILIZAÇÃO GESSADA, POR USO/SESSÃO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60022264','TAXA DE IMOBILIZAÇÃO NÃO GESSADA, POR USO/SESSÂO','TRS');
insert into sch_sisauc.procedimento_base values ((select nextval('sch_sisauc.procedimento_base_id_seq')),'60033568','TAXA DE REGISTRO DE INTERNAÇÃO','TRS');